### ISSUE TITLE
Patterns collection advertised on the website but removed from the Section block?

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1027]
### Description:

There is a section on the product page advertising a "growing collection of patterns" and I wanted to ask if this section is about the template library that was recently removed from the Section block.

If that's the case, would it be possible to hide the section from [the product page](https://themeisle.com/plugins/otter-blocks/)?

![Markup on 2022-07-06 at 16:27:35](https://user-images.githubusercontent.com/26867648/177561305-c39629b6-b912-490d-a9ff-138668fda94a.png)

### Reference:

https://secure.helpscout.net/conversation/1941277856/328595/

**Comment by mghenciu** [comment]
I've edited this, marking it as **Coming soon**. 
As we'll rework this part at some point, and it will be included in Otter in a way or another.
https://themeisle.com/plugins/otter-blocks/ >>
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/52494172/177957288-ec352481-4a33-4573-a1c0-62f7e71d1c19.png">

https://themeisle.com/plugins/otter-blocks/demo-blocks/ >>
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/52494172/177957339-642f5709-75d8-40ce-b811-fe30b95e2faa.png">

Let me know if this sounds good, @HardeepAsrani .

**Comment by JohnPixle** [comment]
Just a note, perhaps we can look into integrating the upcoming core modal, as explained here. https://wptavern.com/gutenberg-13-6-adds-pattern-modal-support-for-custom-post-types-expands-creation-of-template-types

**Comment by mghenciu** [comment]
> Just a note, perhaps we can look into integrating the upcoming core modal, as explained here. https://wptavern.com/gutenberg-13-6-adds-pattern-modal-support-for-custom-post-types-expands-creation-of-template-types

We'll need to think about this **both ways, Free & Pro.**

One solution could be to append some free Patterns in the Core Modal/Library (which I think it's possible), and long term have either an integration with TPC or another type of modal, where we can label some patterns as Pro.
That's why I suggested to have our Modal, because in the Core one - we can't lock and label Patterns as Pro.

We'll talk more about this, when TPC is standalone, in a solid shape.

**Comment by JohnPixle** [comment]
@mghenciu good points, I totally agree with what you say. I am also a big supporter of having our own modal, and manage pattern-related things there. But since we dropped it (temporarily i believe) we must see how we can make things work with the least of friction.

For the record, my opinion is that **I don't find it a good UX practice to require another extra plugin (TPC) for Otter users to be able to import PRO patterns.** I believe the product must have a  "self-contained" pattern library that is easily accessible. This will help with the discoverability and promotion of the PRO assets as well.

**Comment by mghenciu** [comment]
I'll close this one, as the mentioned sections are marked as coming soon.
We'll have another issue for adding the new Pattern Collection.
