### ISSUE TITLE
Dynamic text value small enhancements

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#1032]
### Description:

I tried to play with the Dynamic text value for Otter and I spotted a few small enhancements: 

1. We could list first free ones and then the disabled pro ones https://vertis.d.pr/ObXCrZ, right now we have a list of free, a list of pro, and after a list of free. 
2. Can we add a link in the dropdown after or before the pro ones `Try Premium` with a link to otter/upgrade ? 
3. Should we add the Dynamic icon always on on the toolbar https://vertis.d.pr/dI3NM9 with a standalone cell like text align https://vertis.d.pr/SIbDiB ?  See [Kadence](https://vertis.d.pr/DMQDDK) ,  [Stackable](https://cdn-clibi.nitrocdn.com/OmAxDmvnEDrIbyCCcgEheUGaGtzJEYJA/assets/static/optimized/rev-f02d23c/wp-content/uploads/2021/04/Adding-Dynamic-Content-in-Stackable.gif) 

What do you think @Codeinwp/otter-team

**Comment by HardeepAsrani** [comment]
@selul 

1. Can be done.
2. We don't have much control over there to show a link. I'll try with some JS to see what we can do.
3. We can't keep it in toolbar as it's Formats (like bold or italic) that appear on Format dropdown only. I'll see more to see if there's some way to hook in there but can't think at a first glace at least.

**Comment by selul** [comment]
for 3, those examples managed to do the exact same thing.

**Comment by HardeepAsrani** [comment]
@selul They use a different approach where their dynamic content only works with their own blocks, not with anything selected by the editor. That approach has its own Pros/Cons but it is made very differently where this can be applied to any RichText in the editor.

We can perhaps use their Dynamic Content (for text) on Advanced Heading after all this is done to have that part too, I can see how that can be powerful.

**Comment by HardeepAsrani** [comment]
@selul The biggest Pro of their approach is the Live previews which we can't do in our approach. For the button, I'll see if there's some possible way.

**Comment by mghenciu** [comment]
For what Marius suggested about the Items order (Pro mixed with Free), I would say we can move them, but I would keep them in the same Category, meaning that we should keep the same taxonomy - Posts Dynamic (this could go at the bottom in the list, when using %), Site, Author, etc.

___

Another thing I wanted to add Hardeep, is related to insertion of a Dynamic Value from the toolbar.
I noticed that **it only works if some text is selected. Otherwise, nothing will happen when a user presses on the Dynamic Value area** (as seen in the video), and no feedback is provided why that option is Disabled:

https://user-images.githubusercontent.com/52494172/180790189-6e860403-9a8c-494b-ba85-757cfe4fecaa.mov



What I wanted to suggest here, is to **make it work even when a text is not selected,** and if an user presses the Dynamic Value button -> insert 'dynamic placeholder/fallback text', something like this: 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/52494172/180790159-5b4543ae-5759-4df6-affc-3769c160972c.png">

**Comment by HardeepAsrani** [comment]
@mghenciu ~I took a look, and you can't just add anything unless the text isn't selected, unfortunately. So it can't be added like that, similar to any other format.~

Took some work but got that to work somehow. Hope it passes the QA. 😄
