### ISSUE TITLE
Otter Blocks display issues in demosites network

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1085]
Hello team, I am creating this dedicated issue to tackle some problems we have had recently with some of the Otter Blocks in the demo network.

Sorry for insisting on this but as we focus on Otter Blocks in our starter sites demos (and soon in Raft FSE theme and maintenance pages) we need to address this in a timely manner because it has detrimental effects in the workflow and promotion.

### Primarily affected Blocks

- [ ] **Contact form**
- [ ] **Countdown**

if @mghenciu you have spotted other blocks with similar behaviour, feel free to add them in the list.

### Context
- Blocks are not displaying properly on frontend
- The issues appear primarily on the demo sites network. On a tasteWP instance, Blocks behave properly.
- When re-opening or editing the page and the editor refreshes, the blocks need to be recovered
- If you ask me why [some of the forms appear ok](https://demosites.io/nft-illustrator-gb/contact/) after some period, I have no idea.
- We are not sure 100% if these issues happen to users as well, if they have a similar setup parameters.

URLs of screenshots:
[Coming soon](https://demosites.io/otter/coming-soon-pages/default-coming-soon-2)
[Maintenance](https://demosites.io/otter/coming-soon-pages/default-maintenance-2/)

![Frame 3](https://user-images.githubusercontent.com/4193672/182810851-0f5fbef4-e925-408b-89e1-aebac4fd9c0c.png)

![Frame 4](https://user-images.githubusercontent.com/4193672/182810883-0929f4bc-1683-467d-ada8-6f029ab93bd5.png)

--- 

Thanks for your time and attention!

Keeping in the loop:

@selul @mghenciu @HardeepAsrani @Soare-Robert-Daniel

**Comment by mghenciu** [comment]
Can confirm that from time to time there are some issues where Blocks appear as Invalid. For example a lot of the issues [from here](https://github.com/Codeinwp/neve/issues/3523) where this type of issues, or issues that were fixed just by resaving the page.


Now, I am not sure if it's multisite issue, if it's because of having other plugins and so on. But ideally I think we should investigate some ways of fallback for blocks, see what happens if I have a block from Otter 1.8 and I update to 2+ and so on. 
**And as a mindset I think we should move into a state where new releases don't break older sites.**

Another example here is from the [Architecture Studio demo](https://demosites.io/architecture-studio-gb/), which has the same issue with the Icon Blocks: 
![image](https://user-images.githubusercontent.com/52494172/182830913-6f5686ea-fd6f-4590-b896-4350542ca359.png)

**Comment by HardeepAsrani** [comment]
"And as a mindset I think we should move into a state where new releases don't break older sites."

That has always been the state. Just that things escape in testing. 😀

**Comment by HardeepAsrani** [comment]
Can you update to the latest version and see if some of these issues are fixed?

**Comment by HardeepAsrani** [comment]
I see it also happens with Icon List & Icons block too, right? Any other blocks that face the similar issue?

**Comment by JohnPixle** [comment]
I have not spotted any other blocks with similar behaviour to be honest.

I also tried to set up a multisite at tastewp to see if Multisite setup is causing the issue, but [things are working properly](https://collectend.s3-tastewp.com/5-2/) so far.

**Comment by mghenciu** [comment]
Here's the [demosites Staging](https://staging.demosites.io/) @HardeepAsrani.
Unfortunately there's hasn't been a re-sync between **Live** and **Staging** for some time, so the pages mentioned by John, are not present on Staging. 

Maybe you can start a re-sync, and see later if those issues are also present on Staging.

**Comment by mghenciu** [comment]
It happened today again, when Shubham (web design intern), tried to replace the old WPform [from here](https://demosites.io/fitness-gb/contact/) with an Otter Form .
In the editor it looked ok:
![editor_form](https://user-images.githubusercontent.com/52494172/183898589-62cd4deb-9273-445d-8826-13a44dd676fe.png)

___
but in the Frontend it was broken:
![preview_form](https://user-images.githubusercontent.com/52494172/183898637-936bee3d-474d-40cc-b629-53eba3edf720.png)

___
After I edited the pages, and recovered the Blocks, it works fine now.
He is using Windows & Google Chrome.
