### ISSUE TITLE
Pattern Library

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1134]
### Description:
We will add a Pattern Library to Otter, which will replace the Templates Library that we previously had in the plugin. Here are a few things that I want to mention for us to discuss before we reach start designing/implementing:

- Will we just use the Core Patterns UI and/or our UI?
- If we have our UI, where do we add it? In the Section like before? I hate the idea of it being in the Toolbar by default. It does look ugly there, but I'm ready if that's what you all think.
- Will they exist inside the plugin or in the cloud?
  - If they exist inside the plugin, then nothing much to discuss.
  - If they exist in the cloud, then the first time the user imports them, they will be imported and stored in a CPT for the subsequent imports + only after the initial import will the pattern start appearing in the Core UI as we can't display non-local patterns there.
- As mentioned in the meeting, for the Pro patterns, we will be using the Templates Cloud API.
- Do we just make quick patterns for users to use, or do we also have full-page designs?
- We will also implement a quick feature (nothing complex) where users can select any block(s) and save them as patterns that will be stored locally.

Thoughts @mghenciu @JohnPixle?

**Comment by JohnPixle** [comment]
Thanks Hardeep, here are my thoughts:

**> Will we just use the Core Patterns UI and/or our UI?**

Well, a custom UI will be helpful if we want to better manage and promote PRO assets (patterns, templates etc).  It's a highly more flexible setup.
This does not mean that we should consider ways of being able to use the core pattern UI efficiently.

Perhaps Otter (Free) can register let's say 16 patterns into the core Pattern inserter. Otter PRO can then register another 40 PRO patterns in the inserter, would this be possible? This way we can avoid a custom library, by simply exposing more or less patterns based on otter version (free vs pro)

**> If we have our UI, where do we add it? In the Section like before?**

Section was not ideal for me to be honest, but not in toolbar either. We'll work it out. Perhaps as a trigger button inside the editor. We'll mock it up.

**> Will they exist inside the plugin or in the cloud?**

This is an existential question, not sure.

**> Do we just make quick patterns for users to use, or do we also have full-page designs?**

I think there will definitely be a user expectation for page templates as well. And we can build some useful things such as woo singles using the PRO otter blocks and dynamic content.

**> We will also implement a quick feature (nothing complex) where users can select any block(s) and save them as patterns that will be stored locally.**

That would be insanely good. Will the user be able to edit the pattern later if he wants to?

**Comment by HardeepAsrani** [comment]
> Will the user be able to edit the pattern later if he wants to?

Yea, it will be saved inside a Custom Post Type inside Otter Menu (which will become a Top Level menu in Dashboard) and the user can edit/delete or whatever.

**Comment by HardeepAsrani** [comment]
@mghenciu We will keep the images up on demosites. Is that fine or do you recommend something else?

**Comment by mghenciu** [comment]
> @mghenciu We will keep the images up on demosites. Is that fine or do you recommend something else?

**what images? the ones used in the Patterns?**
If so, I think using demosites.io it's ok. We have there all the images related to Starter Sites - including thumbnails.

**Comment by HardeepAsrani** [comment]
@mghenciu @JohnPixle Can we get a design for this? For now, we have two things:

- Patterns
- Custom Patterns that we will allow users to save
- Maybe a feedback panel for user feedback/reports/requests

For reference, here's how Core's panel looks. Also, we need to decide how we users get to the popup. From a block? From some menu? Or just by adding an "Otter Templates" block.

Keep in mind that we shouldn't limit the height of the pattern grid as different patterns will have different heights that will need to keep the same for the live preview.

<img width="1188" alt="Screenshot 2022-10-21 at 8 53 05 AM" src="https://user-images.githubusercontent.com/2649903/197104318-0c15e2cc-83c9-4836-a797-f2e225945570.png">

**Comment by selul** [comment]
@HardeepAsrani how is this different from the one that we retired? Except that this is a different UI? 

I think this would need to be better researched before moving this forward.  How we will maintain the patterns? Where do we keep them? 

In order to offer a pattern library we need to keep adding new ones, is this sustainable?

**Comment by JohnPixle** [comment]
I think it would make sense at this current point to brainstorm and do more research on this, but not rush into the actual implementation. I feel we are opening too many fronts at the same point.

I am definitely not against the idea, as I believe it will have some advantages. But looks like definitely need to work more on other areas of the product, before engaging with this one, in order to avoid back and forth revisions.
 
Here are some thoughts though.

1. It might be a good idea that this Otter Pattern library can be a PRO feature, and add more to the perceived value of the PRO version of product. 

2. Apart from PRO patterns, the library can introduce FSE page templates, with query loops etc. Something which of course will require us to fine-tune the integration of Otter in the context of FSE templating.

3. One other thing we can introduce is Landing / Coming Soon / Maintenance pages. This way we can cross-sell them in Manty. (Unlock premium Landing / Maintenance / Coming Soon templates with an Otter PRO plan).

4. Wireframes? Just an idea, this needs more thought, but we could perhaps integrate a Wireframes section. 

5. "Conflict of Interest" with our Cloud Templates plugin. This is important, we'll need to see how it will make sense in terms of sustainability. We don't have the bandwidth to curate and keep both libraries updated. Since CTP is going through a "compatibility" phase this period, perhaps we should wait for things to cool down, and see what our options are.

If we want to focus all our efforts into putting patterns, wireframes and templates in the CTP, we can discuss that as well and see what makes more sense.

**Comment by HardeepAsrani** [comment]
I discussed more with Marius on Slack and we think it might be best to pause this for now. With Otter Pro sales being low, better to not add more things that we will have to maintain if we decided to reduce the amount of resources we focus on Otter.

About the research, I suppose many of these ideas can be used with Neve Custom Layouts and TPC.

**Comment by JohnPixle** [comment]
Makes sense, thanks for the update 👍🏻

**Comment by HardeepAsrani** [comment]
As discussed in the meeting, will close this now as we have Templates Cloud as part of Agency, and doesn't make much sense to have an additional Library.
