### ISSUE TITLE
Add float mode to Sticky

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1139]
### Description:

A feature to allow some block/section to float to top/bottom always, regardless if the item has been scrolled or not. And a detection to notify user when more than one item has the same settings.

**Comment by selul** [comment]
I think this can be extended to bottom/top/left/right

**Comment by HardeepAsrani** [comment]
Also: It should only be available for top-level blocks, not for child blocks.

**Comment by mghenciu** [comment]
Sorry for the late reply.

I am curious **what would be the other use-cases for this type of feature** (except the one with the countdown we are working on), and **why we didn't went for the Popup block instead of adding it to Sticky**?

I am not saying this is a bad idea, just want to make sure we are not making a step that will be hard to revert back later, when we scale this.

_Full disclosure, I may be biased by how [Blocksy approaches](https://creativethemes.com/blocksy/docs/extensions/pop-up-content-block/) this type of content block, but my main concern here is that will make the sticky feature more complicated, and also adding more edge cases with the whole Parent/Child, Sticky/non sticky, etc._


The one from Astra, is made with [ConvertBox](https://convertbox.com/), a service for Modals:
![image](https://user-images.githubusercontent.com/52494172/188152042-481c06ff-8872-469a-9070-fa211df60b22.png)

___
**How I see this overall feature (popup-sticky/modals) to be working in future > as an user:**
- I can create a informative popup that's visible just on a single page, and users can't scroll or do anything on the site, until they didn't interacted with the Popup (those popup that ask you to confirm you age) - non dismissible 
![image](https://user-images.githubusercontent.com/52494172/188152242-dfd90a11-10be-4e8e-8ce2-37e1d2cd8fc6.png)

- I want to create a promotional popup, promoting the free delivery service we are providing for only certain categories in our shop (Ceramics & Pottery) - dismissible
- I want to create a small ribon that will stick to the bottom of the screen, and inform users that our site is using cookies - dismissible:
![image](https://user-images.githubusercontent.com/52494172/188152125-802dcb8e-2510-4dd1-8f4e-01e9ba4701e7.png)

- I want a promotional popup on my eBook page, after the user spent a certain time on that page
- I want a dismissible popup inviting users to Subscribe to our Newsletter:
![image](https://user-images.githubusercontent.com/52494172/188151124-cb836911-6b6f-48ca-ac4c-35ef88a23298.png)
- I want a promotional popup, that will have a Countdown inside, and when finished - it will close the Popup:
![image](https://user-images.githubusercontent.com/52494172/188152561-0868ffe3-ff2c-4f39-8c1b-6c0f6dc30b43.png)
- With Plugins like [NotificationX](https://wpdeveloper.com/pop-up-notification-bar-elementor/) or Popupmaker, you also use the popup idea when creating sticky notifications toasts, and those are controlled from one place.

**Comment by HardeepAsrani** [comment]
@mghenciu I agree that at some point we can do something similar with the Popup too but it does make a basic feature for a Sticky extension to allow users option to stick things to top/bottom.
