### ISSUE TITLE
Displaying live preview of Dynamic Values

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1181]
### Description:

Some way to display a live preview of the data in Dynamic Values.

Keeping in mind that we can't mess with the DOM to update the value of the text itself.

**Comment by selul** [comment]
my idea here is to have like a data-preview attribute attached to the preview span/div and have a CSS rule inside the editor which uses the data-preview attribute and displays it instead of the placeholder.

The advantage here is even if we save that inside the DB, as long as a rule is not present in the front end, it will be redundant. Also, we can strip that on save. 

Something worth mentioning here is that content prop works only with pseudo-classes, so we need to think of some CSS magic to accomplish this. 

the question is whether filling the data attribute dynamically based on the post will work, @HardeepAsrani ?

Do you have better ideas @preda-bogdan @abaicus @Codeinwp/theme-dev @Codeinwp/otter-team

**Comment by abaicus** [comment]
I think that using the `content` rule is a good idea. As long as we use a span nested inside the block, it should inherit its style. Something like this would do fine, I think:

```HTML
<div class="wrap-with-styles">
  <span class="dynamic-data-preview" data-preview="Content is here"></span>
</div>
```

```css
.dynamic-data-preview:after {
  content: attr(data-preview);
}
```

**Comment by HardeepAsrani** [comment]
@abaicus Yea, Marius and I talked on Slack and decided that a lot of issues that we are facing with content property not being used inside pseudo can be fixed by adding a child element.

**Comment by JohnPixle** [comment]
I agree, this is a much needed, especially in the context of single post and page templates etc.
Even Elementor does something similar when working with [dynamic content](https://elementor.com/blog/dynamic-content-elementor/). Definitely the context in different than the GB editor in this case, but the logic is similar.

![Screenshot 2022-09-07 at 10 38 00](https://user-images.githubusercontent.com/4193672/188818140-fbc7ccfc-5210-4ba0-a105-b9a95a612b26.png)


### Default preview? 
By default, the preview pulls the content from the latest post or page, so the user does not even need to select a post from the dropdown, to initiate the preview. I think this is a good UX practice. IF the user wants, he can choose a different post to preview content from. 

On another thought, this dropdown that @mghenciu shared must 100% be there in the custom layouts sidebar, when the user is building a template. Let me know your thoughts, and if you see any technical struggles.

@Codeinwp/otter-team

**Comment by HardeepAsrani** [comment]
I had a question for design team: https://www.loom.com/share/4d2072ac1f4f4df3bb8013bc5ad02321 @Codeinwp/design-team

**Comment by HardeepAsrani** [comment]
One more thing:

Because we are using the CSS pseudo-class to make this happen, we can only preview plain text and not any HTML, for examples Category/Tags in Dynamic value are supposed to render Links in the frontend. In this case, should we just display plain text by stripping HTML tags or not display at all?

For things like categories, I personally feel it makes sense but there might be situations where the styling in front end might be so much different that the design in the editor won't really be a representation of how it will look in the front.

So which compromise is better in your opinion?

**Comment by selul** [comment]
@HardeepAsrani my understanding was that the preview will happen in real-time, that's why we used CSS pseudo-class, not that we need to click a button.

I find that the fact we can't preview HTML is a pretty blocker situation since post_content is important to be rendered.

**Comment by HardeepAsrani** [comment]
@selul You can ignore the button, it's a prototype.

And we, even if we could, would've not previewed the_content inside a post. If you're on a single post and you add post content, you're basically creating an infinite loop. So that's not an issue, I doubt any plug-in will ever try to render Post Content, just like the Core also avoids to render it.

**Comment by selul** [comment]
How you can build a single template with custom layout without being able to preview the content ? On 18 Sep 2022, at 16:47, Hardeep Asrani ***@***.***> wrote:﻿
@selul You can ignore the button, it's a prototype.
And we, even if we could, would've not previewed the_content inside a post. If you're on a single post and you add post content, you're basically creating an infinite loop. So that's not an issue, I doubt any plug-in will ever try to render Post Content, just like the Core also avoids to render it.

**Comment by JohnPixle** [comment]
I think we should make a distinction between how the post content preview works inside a **single post** VS inside a **single post template**. I believe what we are more interested in now is the case of a Single Post Template, either in the Custom Layout context, OR in Full Site Editing in the future..

## Single Post
In the first case (single post), Hardeep has a point, because it will create an infinite loop, and this is why even in Core, the post content cannot be previewed. Screenshot below is when you add a post content block inside a single post.

![Screenshot 2022-09-18 at 19 41 02](https://user-images.githubusercontent.com/4193672/190918346-a91a2fcf-6b5d-4e9f-9e2a-c71b7a6e0984.png)

## Single Post Template
In the context of a **Single Post template,** Core also makes use of generic placeholder content, instead of the real content.
The screenshot below is from Raft, when creating the Single Post template. 

![Screenshot 2022-09-18 at 20 03 21](https://user-images.githubusercontent.com/4193672/190919409-05c92c69-2294-42ee-9fe1-4ec4691a79ef.png)


This is not optimal, I agree, and we definitely need to at least try to find a way to preview the actual content of a Post when working on a Template.

## Elementor 

Can we look into how Elementor approaches this? [I had commented](https://github.com/Codeinwp/otter-blocks/issues/1181#issuecomment-1239041560) a few days ago on the Elementor approach.

Also, might be worth noting the following in the Elementor approach:

- When working on a single post or page, the "Post Content" widget (the equivalent to the post content block in GB) is not available. So the user cannot break things by creating an infinite loop.

- The "Post content" widget is only available when the user is working on a **Single Post or page template**. In this case, the post content widget is available.

- ONLY in the case of a **Single Post / Page Template** they use a Preview dropdown to select the post / page from where the dynamic content will be pulled from. This makes sense, because when the users build a Single Template, t is really helpful to see an actual post content rather than a generic placeholder.

![188818140-fbc7ccfc-5210-4ba0-a105-b9a95a612b26](https://user-images.githubusercontent.com/4193672/190918888-8551ccb8-7ca6-43c1-976c-e71117b38c7c.png)

**Comment by selul** [comment]
Ok, in this case we would need to re-evaluate the solution as we need the post content.

**Comment by mghenciu** [comment]
Quick question about this @HardeepAsrani: **will/how the Fallback functionality will work in this case**, right?
Overall, I think it's useful to keep the fallback option.

**Comment by HardeepAsrani** [comment]
> Quick question about this @HardeepAsrani: will/how the Fallback functionality will work in this case, right?

It works as normally. If you don't have anything, we show the fallback.
