### ISSUE TITLE
Sticky Float option not sticking to Left

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1195]
### Description:

Here: https://themeisle.com/plugins/otter-blocks/upgrade/

If you inspect the Sticky div, you will see we needed to add `left: 0;` CSS to make it sticky on the left of the screen. Users shouldn't need to add CSS for basic setup.

It seems to be working fine with a few themes I tested (mostly default).

### Expected behaviour:

- To sticky to left properly when used with left side offset.

### Current behaviour:

- Appear somewhere in left/center.

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.144

**Comment by Soare-Robert-Daniel** [comment]
When trying to add a full-width container to the float mode, things are getting complicated because of the inconsistency of the block `width`. 

If you set `100%`, it will inherit the size from where it is placed on the page when `left` is set. And this creates confusion since the percentage is not related to the viewport.

When a block has `alignfull` and `100%` width set, the `left` prop is skipped. But edge cases still exist, like on the site.

The conditions are: https://github.com/Codeinwp/otter-blocks/blob/59651ad84b28b2ab593eb0c466e232626b0f180d/src/blocks/frontend/sticky/index.ts#L381-L387

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Is there a solution?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani putting more options will offer great flexibility for many edge cases. But it will take a lot of space, which will be a problem since we only have one tab for Sticky.

A better option will be to make a dedicated Sticky Container block where we would have a lot of space to add a plethora of options.

Making a block sticky from the menu is very handy for fast things. But for more complex cases, we need something more robust like a dedicated Block.

**Comment by Soare-Robert-Daniel** [comment]
Added an exception rule for Neve in #1339
