### ISSUE TITLE
Adding the possibility of using Slider to showcase text

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/otter-blocks#1278]
### Description:
A user asked if there is a possibility to add text instead of images inside the Slider block.

After providing a solution ( using Canva to create her own design and just insert the image ), she mentioned that using an image with text will not create the desired result with the search engines.
### Alternatives:
We can leave it as it is.

**Comment by JohnPixle** [comment]
Hey @AndreeaCristinaRadacina ! We recently discussed this with Hardeep and it turns out it's a bit challenging to make this adjustment to the existing Slider Block. It will be easier to create a new Content Slider from scratch, which is something we plan to do in the near future.

Here is the issue for reference: https://github.com/Codeinwp/otter-internals/issues/8

Hope this helps, thanks for submitting!

**Comment by AndreeaCristinaRadacina** [comment]
That sounds great! Thank you, @JohnPixle!
