### ISSUE TITLE
Otter icon on the toolbar is too intrusive

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#1333]
### Description:

Besides bringing value to our users, I think we should do our best to don't create trouble. Personally, I find the Otter icon on the toolbar by default, not a good practice looking at the features that are listed there.

Export JSON - I think this should not even be enabled by default, how often and by what % of users is being used to justify the space?
Copy/ Paste Styles? - I think some users would use it heavily, others not

While Export, as I mentioned probably, can be off by default, the copy-paste styles I think it can go into the extended toolbar menu, vs on the main toolbar. As mentioned on the Form block review, the settings should be ideally ordered by usage.

### Alternatives:

Do nothing.

@HardeepAsrani curious about your thoughts.

**Comment by HardeepAsrani** [comment]
Will cc other people involved in this decision @JohnPixle @mghenciu @Soare-Robert-Daniel 

Basically the idea was to make these features of Otter, like Copy/Paste, Sticky to Top, and so on to be more visible for users. Previously, we it was hidden in the Eclipses menu which was only easy to find, so most would just miss it if they didn't explore to see, plus that way also users wouldn't know that this feature was coming from Otter, not a Core feature.

Another issue here was that it wasn't possible to expose these features to Block-based Widgets screen as it didn't allow us to add those options to Eclipses menu.

**Comment by ineagu** [comment]
That's a fair point, we can probably explore one by one those things.

1. For giving exposure + choice a way is to have a full-screen onboarding when users can choose : Do you think you wanna use sticky bocks? Copy paste styles etc.
2. We can leave the icon there as it is, but add a "Remove this icon" or "Move those settings to Eclipses Menu", which users can click and have them there.
3. I still think that export json probably can be disabled by default and we can figure out how to make sure users is asked about.

**Comment by ineagu** [comment]
I think the 2nd option solves all your concerns. There is exposure, easy way to find and work in block-based widgets. Just that now users would have a choice to easily move it away if they don't use a lot. Similar as you can re-order items on your iPhone.

**Comment by JohnPixle** [comment]
I personally think that the Otter icon helps in the overall UX and discoverability of the features, and also allows users to have a clear mental grouping of Otter-related options.

It also helps the user understand which of the features are by Otter, and which are from core.

If you'd see _Copy Styles_ for example under the Ellipsis menu, how can you understand that it's an Otter feature and not a core one? 

I would also suggest that we consider adding more sections of Otter-related settings under the Otter icon. For example, Dynamic values and links would definitely fit in there.

![Screenshot 2022-11-17 at 1 46 53 PM](https://user-images.githubusercontent.com/4193672/202438727-cf912635-512f-4e55-842b-cf027ffd4658.png)

What @ineagu said about having an option to remove the icon altogether might be a solution. But I think that this option would make more sense in the plugin settings instead of the dropdown itself. I feel it's UIX gravity is too much to be squeezed in such a small area. 

Let me know your thoughts.

**Comment by HardeepAsrani** [comment]
We can't have Dynamic Value/Link thing there as it's a format and it needs to be inside the Format thing.

And yes, I agree, allowing users to remove it seems like a good idea. I can see some finding it a bit annoying if they don't use any of it.

**Comment by JohnPixle** [comment]
> We can't have Dynamic Value/Link thing there as it's a format and it needs to be inside the Format thing.

Thanks, was not aware of the limitation. 

What you all think about having the "remove" option in the settings page? Text is just for sample.

![Screenshot 2022-11-17 at 2 16 20 PM](https://user-images.githubusercontent.com/4193672/202444079-32295112-bc02-4d8a-8fef-8d7245616575.png)

**Comment by mghenciu** [comment]
Valid suggestion @JohnPixle . And we can have that ON by default, right?
Or do you guys think it should be OFF by default.

Overall I think the 'truth' is somewhere in the middle. As we initially added the Icon to increase Otter features visibility, and I was preparing to say that other Block Plugins are also doing this. And yes, **Stackable is also doing this, the difference is that we add Otter on almost every block on the page - ours, core, 3rd party (which can be annoying if you neve use it)**, while Stackable adds the Icon to their blocks only.

**Comment by JohnPixle** [comment]
Yeah, that's true Mihai. Most of others plugins are doing it, but usually only on their blocks.

I suggest we have it toggled on by default.

**Comment by ineagu** [comment]
okay, I think it is better than currently, but still not ideal in my opinion, since at this stage of the product the focus should be delivering the best ux we can, people don't care that we worked at stuff that we wanna highlight and don't know how :D .

@HardeepAsrani I was wondering if we can't have those in the right sidebar? where do we have the visibility/animation settings? 

I see that if I make a block sticky, I get the setting in the right side for it, is hard to get my head around having those settings in the toolbar, and seems out of place.

Also, a potential idea for making it clear that those are otter settings is to have the otter before the setting ( here is after) , but you get the idea; https://vertis.d.pr/i/8boc5e .

**Comment by HardeepAsrani** [comment]
Once you click in it, you get the Otter logo there so it's not an issue. Like copy/paste styles don't make much sense in the sidebar. To make it easier, we can have a toggle in the Otter Menu itself to make it easier for user maybe?

**Comment by ineagu** [comment]
I think John was concerned that it would get too crowded, which does make sense and is not the most elegant way.

We can probably wait until things are more standized, since that toolbar can become a mess if 5 other plugins would do the same thing.

**Comment by JohnPixle** [comment]
To briefly comment on some of your points:

_Ionut said:_

>  **I was wondering if we can't have those in the right sidebar? where do we have the visibility/animation settings?**

I will agree with Hardeep that the copy / paste will make more sense in the block toolbar rather than in the settings sidebar. 

---

_Hardeep said:_

> **To make it easier, we can have a toggle in the Otter Menu itself to make it easier for user maybe?**

I would not advise that, unless you are talking about the Otter settings sidebar. In this case yes, we can have the toggle there instead of the plugin settings, It's even more accessible. This sis where I mean:

![Screenshot 2022-11-18 at 11 28 36 AM](https://user-images.githubusercontent.com/4193672/202668467-2a8a23bf-f414-4b92-8785-1ce3bc47d4b4.png)

_Ionut said:_

> **We can probably wait until things are more standized, since that toolbar can become a mess if 5 other plugins would do the same thing.**

👍🏻 this makes sense too. I think it is a good idea not to rush with fixing this, as it's highly possible that the overall consensus regarding the toolbar might change in the future versions.
