### ISSUE TITLE
Custom CSS styles missing on Archive pages

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1373]
More info here: https://wordpress.org/support/topic/styles-are-missing-in-main-page/#post-16226757

We can see how to make it work properly and also check if the user's snippet works without any issues.

**Comment by Soare-Robert-Daniel** [comment]
After various testing, the Custom CSS works, but not sure about the context described by the user.

With Astra theme and a plugin for [creating pages with tags and categories ](https://wordpress.org/plugins/pages-with-category-and-tag/)

> It also doesn’t work in search pages if there are more than one result.

I do not know how it is supposed to work on the search page since when listing the first part, the content is only a `p` tag with a text.

Search Page


![Image](https://user-images.githubusercontent.com/17597852/234848727-df5e90d8-2c6e-46b3-857e-cf929e0db32d.png)


The page


![Image](https://user-images.githubusercontent.com/17597852/234848868-4d897b11-06b0-4f21-bf40-cfb1626f3cd1.png)

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel If that's the case, then it's intended, given blocks aren't being rendered just text is. I think we can close it for now and come back if there are more reports. It's an old issue and there hasn't been any more such reports.
