### ISSUE TITLE
Add option for updated date in the Posts block

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1432]
### Description:

The Posts block can show the publish date in the metadata but not the updated date.

<img width="1954" alt="Markup 2023-01-06 at 16 20 01" src="https://user-images.githubusercontent.com/26867648/211030965-916d1a2d-8d3e-4d24-b88b-36da33a01a97.png">

### Alternatives:

Is there a code snippet with a filter that we can provide as a gist in case this won't be implemented?
 
**Reference**

https://wordpress.org/support/topic/showing-posted-on-date-instead-of-updated-on-date/

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu It doesn't make much sense to display updated date here when you can only query by the latest posts, so when you're displaying, let's say a list of 5-10 posts, based on their post date, having when this was last updated isn't very relevant information. Thoughts @mghenciu?

**Comment by mghenciu** [comment]
I think here are 2 use-cases which are very similar, @HardeepAsrani , yet I am not sure which of the the user is mentioning.

1. **Showing the actual update date with label**
In this case, as I user, I would like to show in the Posts Meta - the **Updated date**, to let the visitors know when the post was updated.

2. **Refreshing posts**
The other way of using this, is by using only the **Date** in the meta, and the user can choose if that date is Published date or Update date. This way a admin can update some minor things on a post, and make it look like the post is newer (I think it's a common practice in the blogging space).

How we can approach this, is similar to Neve, meaning that we would drop the **Posted on** keywords and use **only the numbers/date**. And in the UI the users can choose if they want to use there the post date or the updated date:
![Screenshot 2023-01-09 at 14 03 38](https://user-images.githubusercontent.com/52494172/211303877-a9bad474-ac57-420f-9519-97c67974caf1.png)

Also if we do this, I think it would make sense to apply the same thing on the Dynamic Value - Date, as when building a Posts Query Loop, maybe I want to display the Updated date instead of publish date.

Hope it makes more sense now.

**Comment by HardeepAsrani** [comment]
@mghenciu In the Dynamic Values, you can get the Updated date. For here, it's going to be a list of latest posts so won't showing last updated date in a list of 5 latest posts not very relevant?

**Comment by mghenciu** [comment]
The Posts Block won't show only the Latest post, as it can be configured to a **certain category or else**.
For example let's say I have the homepage, and there I have a small section with a certain category of Featured posts (they are static), similarly how it's on codeinwp: 
![image](https://user-images.githubusercontent.com/52494172/211307121-0aa0aaac-6831-4cb5-a104-828af4fa4117.png)

I want to have the date on those posts Meta, but **not the published date**, as it would be very old; rather I would want to show the updated date, making those posts look updated/new.

Or for example let's say I have a Top Articles section with, Best JS Frameworks, Best Design Tools, Best Python Courses.
If I have the Date in meta here, for sure as a visitor, I would love to see that the post is fresh/updated, not from 2019: 
![image](https://user-images.githubusercontent.com/52494172/211307987-f6a7c62c-9b0c-4f2c-b91d-9b94567f34af.png)

___
So overall, this feature may be a snowflake/very rarely used, just in some cases.
