### ISSUE TITLE
Wrong author in Review Schema

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1491]
### Description:

It seems like in many cases Review Schema shows the wrong author. I have personally not been able to reproduce it but I've seen a couple of examples. Perhaps we can try with sites with multiple authors to see if we can reproduce it.

We are using a function which has been deprecated https://github.com/Codeinwp/otter-blocks/blob/master/inc/render/class-review-block.php#L276 and can be replaced with `get_the_author_meta`

### How to reproduce:

1. Not sure.

### Expected behaviour:
To show the author of the post.

### Current behaviour:
Sometimes showing wrong author.

### Reference:

https://staging-coinbureau.kinsta.cloud/guides/test-post-using-consulting-tag/

### Technical info
* WordPress version: 6.1.1
* Plugin version: 2.2.2

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/2148641307/355309?folderId=931544

**Comment by arinaturcu** [comment]
I think the issue here is the same that we had on Social Sharing block, the `get_the_author()` will give wrong values when put is contexts like widgets, archives or custom layouts (same as `get_the_title()` from the sharing block).

I don't know if this is the case of the user, since [this post](https://staging-coinbureau.kinsta.cloud/guides/test-post-using-consulting-tag/) does not exist anymore. But what do you think about appling the same strategy as here https://github.com/Codeinwp/otter-blocks/pull/1430?

@HardeepAsrani

**Comment by HardeepAsrani** [comment]
@arinaturcu you can see the same issue here: https://www.coinbureau.com/review/phemex-exchange-review/ - while I think it can benefit from a similar situation but this issue isn't that, it's somehow it got the wrong author. I've asked the user if he can give us access to his website so we can test why this might be happening. It might be something else too, maybe the user is using Reusable Block for review, so let's see.
