### ISSUE TITLE
Regenerate styles doesn't work on multisite

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1604]
### Description

The button for regenerating the styles is disabled on a multisite environment.

### Step-by-step reproduction instructions

1. From the network page, access the Otter settings page and you will see the Regenerate button disabled even if you are Super Admin
2. Try accessing the Dashboard of a subsite within the multinetwork and the Otter settings page in the subsite -> the Regenerate button is still disabled.

### Screenshots, screen recording, code snippet or Help Scout ticket

![otter-regenerate-disabled](https://user-images.githubusercontent.com/26867648/230850815-41681b84-a70d-4a25-bd33-e196476a9538.png)

Reported here: https://secure.helpscout.net/conversation/2204728707/364531/

### Environment info

https://pastebin.com/eVb8nNEQ

### Is the issue you are reporting a regression

No

**Comment by arinaturcu** [comment]
@stefan-cotitosu I created a network, added some Otter blocks with CSS in one of the subsites, and the `Regenrate Styles` button for that subsite works fine. Am I missing something?

**Comment by vytisbulkevicius** [comment]
@stefan-cotitosu,

I checked this one and I can see it disabled as long as there is no Otter widgets in use. I used Otter in one of the posts and then button became active because CSS was created that could be re-generated (before there was none).
So behavior is expected.

I'm closing it, let me know if you have any additional findings.
