### ISSUE TITLE
Review Comparison table not taking Reusable Review blocks into account

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1622]
### Description

A user reported that when he is using Review Comparison Block, it's not taking Review Blocks saved as Reusable Blocks into account.

Looking into the code, it should technically work: https://github.com/Codeinwp/otter-blocks/blob/master/plugins/otter-pro/inc/server/class-filter-blocks-server.php#L96 - but we still investigate to confirm if that's the case.

### Step-by-step reproduction instructions

1. Create a Review Block and save it as part of a Reusable Block.
2. Create a Review Comparison Block and make sure the Review block from the Reusable Block appears and works in both the back/front.

Also the user reported that if you put the block inside Accordion, it looks messed up with Reusable Block.

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
After some investigation, it seems that reusable blocks do not `innerBlocks`, making the block invisible to our hooks.

Affected lines: https://github.com/Codeinwp/otter-blocks/blob/df4e009eb5939e73fc121ab6dc006bc04fb1ca9f/src/blocks/plugins/css-handler/index.js#L129-L140

Debugger visualization:

![Image](https://user-images.githubusercontent.com/17597852/236455061-8a12e157-de3a-4280-aeaa-28d273520d19.png)

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani This is a miserable situation. We need to pull the data for reusable blocks, and also possible to the same things in the https://github.com/Codeinwp/otter-blocks/blob/master/plugins/otter-pro/inc/server/class-filter-blocks-server.php#L96

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel checkForReviewBlock part is only for adding the meta to the post if the post contains a Review block (not inside a Reusable Block), so does it make any difference? Will be good to make sure there aren't any issue with meta being added where it isn'.t

**Comment by Soare-Robert-Daniel** [comment]
In https://github.com/Codeinwp/otter-blocks/pull/1655, I made a change that allows `checkForReviewBlock` to mark posts with product reviews in reusable components, but in the backend, we also need to pull the data so we can display it. 



![Image](https://user-images.githubusercontent.com/17597852/236812911-9f503e71-5a43-485c-93be-ce7e10cd8fcc.png)

If we continue on this route, it might be a problem with duplication since the same reusable block might be reusable in multiple places.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Why do we need to mark posts with product reviews in reusable blocks? We don't need to do it. The post meta should be added in the reusable block's post meta too, is it not?

**Comment by Soare-Robert-Daniel** [comment]
No, it is not added to `reusable block's post meta`.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel In the past, I do remember, it used to work with Reusable Blocks too, so we can try to figure out how to make it work there.

**Comment by Soare-Robert-Daniel** [comment]
Ok, I will check the detection; maybe now there are no longer considered posts.

**Comment by Soare-Robert-Daniel** [comment]
As discussed on Slack, the great issue is that the Gutenberg API does not get the `meta` field for the Reusable Block Post.

![image](https://user-images.githubusercontent.com/17597852/236835285-9d01a9bc-5856-4d37-8eb9-8ac1cc7ad6e1.png)

We will try the following approach:

If the block has type `wp_block`, we will use an endpoint to save the metadata since JS functions seams do to have no effect.
