### ISSUE TITLE
Visual issue in Section's Background & Background Overlay Controls

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#1711]
### Description

Whenever we are using `ButtonDropdownControl` component for popovers, the popover appears far away from the selector in the latest version of WordPress. With the solution, we must test in previous versions to insure it works.

### Step-by-step reproduction instructions

1. Add a section block and open the Background & Content tabs.
2. Click on any control, and the popover will be far to the left, as you can see in the screenshot.

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1244" alt="Screenshot 2023-06-15 at 3 18 23 AM" src="https://github.com/Codeinwp/otter-blocks/assets/2649903/9b7ac394-9628-4419-89f2-3987db57cbbe">

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
The problem is this CSS CSS which adds an extra margin on the left.

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/ec25944e-e28b-44b6-8e52-94d627c8735a)

Since it is a general class selector, I did not find any settings in the `Dropdown` component which can reduce this effect.

The problematic part is the usage of `!important`, which prevents us from overriding the value with basic CSS via `:has` selector.

I was looking to change this component with the built-in one for colors, but the problem is the lack of support for adding background images. Our use case is more powerful that what is provided https://github.com/Codeinwp/otter-blocks/blob/b8bc7341e8c00fe00894640a6b3f4161491e4369/src/blocks/blocks/section/columns/inspector.js#L776-L804
