### ISSUE TITLE
Slider images not rendered if added in Neve's header

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1750]
### Description

A customer reported that when he adds a Slider block in Customizer -> Header -> Header Builder -> Widget Area 1 (for both desktop and mobile view), the images are displayed correctly on desktop, but only a blank area appears on mobile. When I test this on my instance, the images don't appear on desktop, but they do on mobile. There is no error in the Console. He also encounters the issue when he uses a slider from the Smart Slider 3 plugin.

### Step-by-step reproduction instructions

1. Install Neve, Neve Pro and Otter
2. Go to Customizer -> Header -> Header Builder
3. Add a Widget Area 1 component
4. Add a Slider block in that component
5. Repeat steps 3-4 for mobile view as well
6. Check the slider images on desktop and mobile

### Screenshots, screen recording, code snippet or Help Scout ticket

Desktop view on the client's site:

![desktop2](https://github.com/Codeinwp/otter-blocks/assets/86592341/ee1794d2-5c33-495d-91b1-2f7e2808e316)

Mobile view on the client's site:

![mobile2](https://github.com/Codeinwp/otter-blocks/assets/86592341/ef00268a-c381-4a09-95c4-fa15be5b88da)

Desktop view on my instance:

![desktop](https://github.com/Codeinwp/otter-blocks/assets/86592341/405b50ef-b64f-492c-a0bf-9ff367015a6b)

Mobile view on my instance:

![mobile](https://github.com/Codeinwp/otter-blocks/assets/86592341/3bc4ec84-ab50-4fd6-87f2-d8babcf959ec)

Reported [here](https://secure.helpscout.net/conversation/2289018013/375912/) .

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, the issue here is that the CSS is not loaded in the frontend.

Here is how it looks in Customizer regarding the presence of the CSS

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/6fff6b41-be17-48fb-967a-1315ca3c213d)

In frontend 

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/fc73780b-6bea-4800-b510-804732b1e33a)

⚠️ You can see the lack of CSS properties.

----

ℹ️ Following this idea of lack of CSS. I added other blocks, and you can see the missing CSS files.

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/3998ab44-c63e-46c8-86d4-63af01208f04)

🔴 To check if this is an issue with Otter, I installed [another plugin](https://wordpress.org/plugins/essential-blocks/) to see if the same thing happens. And it happens:

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/78bfc191-7d7f-4f97-8c9b-7711f7f3e9bd)

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can we fix it? Given that unlike third-party plugins, Neve and Otter are sister products. 😄
