### ISSUE TITLE
Progress Bar height not same as on Tablet and Desktop

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1776]
### Description

[As reported also here,](https://github.com/Codeinwp/neve-pro-addon/issues/2552)

Progress Bar block **doesn't respect the set Height on Mobile**.
In the example below it set to 13px, but on Mobile frontend is 30px.

I think this should be included on the Visual regression test list.

### Step-by-step reproduction instructions

1. Create a fresh Otter Version 2.3.2  + Neve instance
2. Add the Blocks from below on a page
3. Preview the page on Desktop vs Mobile
4. Notice that **on Mobile, instead of 13px height - the progress bar has 30px**

[blocks-export.json.zip](https://github.com/Codeinwp/otter-blocks/files/12144821/blocks-export.json.zip)

### Screenshots, screen recording, code snippet or Help Scout ticket

![Screenshot 2023-07-24 at 12 56 24](https://github.com/Codeinwp/otter-blocks/assets/52494172/3cf2954e-6216-4a09-837e-ccdcc6727dcb)
![Screenshot 2023-07-24 at 12 56 44](https://github.com/Codeinwp/otter-blocks/assets/52494172/98bd5d24-f84a-4b12-b099-8cefec6005e6)

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani  I remember correctly; this was one because we did not have multiple versions of the height based on the viewport, so we decided to make the mobile version have a fixed width.

Here is how it looks when restrictions are removed.

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/f8f6be9a-4eea-476e-b5d9-b4fe1dea8f3b)
