### ISSUE TITLE
Flip card content trimmed at the top

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#1837]
### Description

When I add long text to the flip card, on both sides, I see scrolling is available on the back of the card, however, the first part of the content is still not visible even with the scroll functionality.

### Step-by-step reproduction instructions

1. Add longer text on both sides of the card
2. Visit the page and hover to flip the card
3. Scroll will be available on the back of the card, however, the first part of the text is still not visible

### Screenshots, screen recording, code snippet or Help Scout ticket

Video of the issue - https://vertis.d.pr/v/sAP5Ja

Reported here: https://wordpress.org/support/topic/otter-plug-in-flip-card-does-not-show-full-text/

### Environment info

https://pastebin.com/aDSngHvG

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
The problem with the big content on the back of the flip is solved by setting the alignment to the top position.

ℹ️ On the front side, the content should respect the size in height since that area does not work well with scroll since is the side that flips.

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/5cab29d8-d580-47ae-9838-e5999d036fad)

@AndreeaCristinaRadacina if we can add this case to Flip docs 🙏  https://docs.themeisle.com/article/1673-popularity-block#flip-card

----

⚠️ I tried to find some CSS solutions, but are not reliable in the current structure of the block.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Anything else we can do here?

@stefan-cotitosu Can you confirm with the user if this solves their usecase?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, for now, just improving the docs.

**Comment by Soare-Robert-Daniel** [comment]
@AndreeaCristinaRadacina, Looks good 👌
