### ISSUE TITLE
Check Otter blocks with Neve/Hestia's sidebar

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/otter-blocks#35]
@radu-themeisle like we talked, you can take a look at the default blocks too, to make sure they work the same as the custom blocks for Neve/Hestia in our custom gutenberg integration
https://prnt.sc/mdpoy1

**Comment by radu-themeisle** [comment]
The blocks had  left/right margins, I deleted them and set the section structure to max-width 1170px. All the blocks use full-width in order to stretch across the page.

**Hestia**
With sidebar, the content overlaps it and there's a negative left/right margin that makes everything look weird:
http://prntscr.com/mdrwmk
http://prntscr.com/mdrw7t In this case, the block covers the sidebar.

Without negative margin:
http://prntscr.com/mdrxnf
http://prntscr.com/mdrxga

In the editor, it seems that the blocks + sidebar have max-width 1170px coming from the theme which makes everything look cramped:
http://prntscr.com/mdrxzu
http://prntscr.com/mds357

Without sidebar blocks look good apart from a padding-top for the section tag making the content not "stick" to the header and creating a white space: https://www.dropbox.com/s/55xi5uf9uojla93/FireShot%20Capture%2051%20-%20Demo%20website%20-%20http___demoimport.local__page_id%3D5115%26preview%3Dtrue.png?dl=0

**Neve**
With sidebar on and "Enable Individual Content Width" disabled the sidebar has 1 letter/row:
http://prntscr.com/mds6m4
With the option enabled: http://prntscr.com/mds6zw

Without sidebar blocks look good: https://www.dropbox.com/s/syyhwxxwwlzxsrw/neve%20without%20sidebar.png?dl=0

I will push an update for the default blocks.

**Comment by radu-themeisle** [comment]
Neve with sidebar renders ok, for Hestia we've included a condition to prevent calculating margins if sidebar exists.

ref: https://github.com/Codeinwp/hestia-pro/pull/2020

**Comment by HardeepAsrani** [comment]
@selul I'm not sure if we should change the templates for this as Templates are obviously not gonna look good with a sidebar, as they're supposed to be on alignWide or alignFull. What do you think @rodica-andronache @selul

**Comment by rodica-andronache** [comment]
yes, this was something related to the theme

**Comment by HardeepAsrani** [comment]
@rodica-andronache Should we close this?

**Comment by rodica-andronache** [comment]
@HardeepAsrani I'm not sure, I would say no. From what I remember @radu-themeisle tried improving the default Otter blocks by using the 'Maximum Content Width' option instead of paddings (similar to Neve/Hestia's blocks), obtaining something like this https://prnt.sc/mjxvg8 instead of the current https://prnt.sc/mjxvv6 but for some reason, I don't know you reverted that. 
What do you think? 💯

**Comment by HardeepAsrani** [comment]
@rodica-andronache Yes, it was reverted because that's an issue with how Hestia handles sidebar and modifying templates for it isn't the best solution. This might cause some other issues with different themes, so we're just pausing this problem for some other time.

I think issues like this can be solved by having a Full Page Template for Gutenberg, as we've done for Elemento templates. What do you think?

**Comment by rodica-andronache** [comment]
@HardeepAsrani I know the best way would be to use a full-width template, but I was just thinking that this solution could help when adding the blocks on any default page from any theme that uses sidebars.
https://prnt.sc/mpu3pr
https://prnt.sc/mpu3wx
https://prnt.sc/mpu43a
https://prnt.sc/mpu4a8
this doesn't seem to be related to how Hestia is handling the sidebars, as it's the same on any other theme. And using the Maximum Content Width instead of the paddings seems to work, for me

**Comment by HardeepAsrani** [comment]
@selul @radu-themeisle @rodica-andronache Entirely your call on this as I'm not great at building templates (a get a bit obsessive with things being even 😞  ). If you think this is the best option then I can revert Radu's changes and we can test and merge.

Also, if we're taking this approach then it will be great for Radu to write small instructions on the basic layout so we can follow the same for all templates, making all of them follow the same structure (hello my obsessiveness). 😄

**Comment by rodica-andronache** [comment]
@selul what do you think? :)

**Comment by selul** [comment]
@rodica-andronache yes I agree with Hardeep. I think we should aim to have a full-width page template for Gutenberg, similar to how we have with Elementor not tweak otter to work with sidebar pages. 

as a sidenote, this is how it looks on 2019 theme with Elementor a similar section http://prntscr.com/msx5ws

**Comment by ineagu** [comment]
but even if we would have a full-width template, this won't solve the negative margin issue right?

**Comment by rodica-andronache** [comment]
ok, I personally don't understand why making these changes would be considered tweaks, I was thinking that's how the blocks should be built, but if that's the case, I guess we can close this 👍

**Comment by ineagu** [comment]
I think we can break this in 2 issues @rodica-andronache to avoid getting all confused:

1. There is a problem in Hestia which makes the blocks override sidebar and need to be addressed in Hestia, not only for Otter but for Gutenberg or any other builder/plugin

2. There is a problem in how the current Otter blocks are built,  appears to use fixed padding which doesn't adapt based on the container size which causes on small containers to look like this: https://prnt.sc/mjxvv6, which is much worse than your example @selul . For me this isn't an issue right now, we should redo the initial blocks either way in next months, but this is a good point to consider.
