### ISSUE TITLE
Test Dynamic Column Resizer

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#48]
![resizer](https://user-images.githubusercontent.com/2649903/52514807-16e04580-2c3b-11e9-8210-bd68d4e4839d.gif)

We've added a Column Resizer which is inspired by Elementor. Since it's in Gutenberg, we need a lot of testing. I've so far not been able to break it but more eyes the better.

You can download it from here (make sure you're using VertiStudio account): https://drive.google.com/open?id=1tSPBOkU4Te225KVByabFcKs956sMsNSC

Things to keep in mind:

- It works best in Full Width.
- It's only for Desktop.
- I've tested in Firefox, so please try with Chrome and Safari.
- Make sure it works just fine with new added columns, columns which were added before this version of the plugin... and most importantly, Template Library.
- Make sure it works in the front-end, as well as after the page is saved and refreshed.
- Sometimes the column will resize in percent tooltip but the width won't change in backend, that's because of the contents which are inside that take more space + padding/margin, so that's not really a bug.

If you see anything, let me know. Thank you for helping!

**Comment by HardeepAsrani** [comment]
cc @ineagu

**Comment by HardeepAsrani** [comment]
Any updates? @radu-themeisle @stefan-cotitosu 😄

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani I've tested it with Neve blocks and tried to create a new one. It works fine, it's a little bit confusing for me that it doesn't work on tablet too.

I've notice that the resizer appears only the right side of the column. So if I have a two columns layout and want to use the resizer, I have to click on the left one to see it.

Is there any input where you can type the columns width like 25% 50% 25% instead of dragging that line between the columns?

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Thanks for taking a look.

1. Yes, it's only for desktop now, just like all other page builders.

2. Good point, we can fix this.

3. No, there's no option to type it so far. In the beginning, I didn't add it because I was little frustrated with this feature, but by the end, I didn't add it like no other page builder add manually typed width. What do you think @selul?

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Apart from the noted down points, is it working just fine for you?

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani Yes, I even tried to create a page with Otter 1.1.4 then update the plugin and everything was ok.

**Comment by HardeepAsrani** [comment]
I'll leave it open for @radu-themeisle to also test

**Comment by radu-themeisle** [comment]
Work and looks pretty good, great job @HardeepAsrani!

My only suggestions/ideas are:

1. Make the columns resize in 1% steps instead of 0.01%. This is something that also annoys me in Elementor when I drag & drop the column size as I never manage to get an integer value (like 27-63 ratio), it's always with decimals and apart from wasting time to get the correct value I don't see the point in having a decimal level selector. In my opinion movin in 1% steps would simplify the UX.

2. In 3+ column layout the resizer has [different lengths](http://prntscr.com/mqr19d ). At first it looks a little weird to me (an extreme example: http://prntscr.com/mqqzr9).
Maybe if we implement the dotted border as proposed [here](#52), then we can integrate the resizer in the border and make it look even regardless of the column length.

**Comment by HardeepAsrani** [comment]
@radu-themeisle 

1. Alright, we can do that.

2. That's why I recommended Wide Alignment to try it out. The child elements add stuff and padding/editor/theme styles which make it this way and we can't do anything about it. :)

**Comment by ineagu** [comment]
I personally think we can go with a much lighter approach here, get rid of the default delimitators you show now and display a simple line along with resize icon only when the user hover the line between columns, it isn't such a used feature I believe to display those by default ( check squarespace )

**Comment by HardeepAsrani** [comment]
It took me a long time to figure out how to do this in Square Space: https://www.useloom.com/share/7dc7a166b19045b2bfaa9eeb952d08f6 😄 - not sure if this is any better since it's completely invisible, similar to how Beaver does this.

Is this what you're talking about?

**Comment by ineagu** [comment]
Yes. I agree, but do you imagine yourself really dragging those around too much? Or let’s say you wanna try or look for it, would you find it? For me current solution clutters a bit. Is like clients worried about how website look when browser window get resized.

**Comment by HardeepAsrani** [comment]
We can show this blue point for dragging only when the user has hovered over the middle of two columns. What do you think? This removes the clutter.

<img width="705" alt="Screen Shot 2019-03-10 at 4 45 51 AM" src="https://user-images.githubusercontent.com/2649903/54078529-9a9b5980-42ef-11e9-8969-a314ec8aeb61.png">

**Comment by ineagu** [comment]
Better :)

**Comment by HardeepAsrani** [comment]
Here's how it will be now.

![Apr-02-2019 03-25-00](https://user-images.githubusercontent.com/2649903/55362295-2d967080-54f7-11e9-9236-e6a3c6f710e0.gif)

**Comment by HardeepAsrani** [comment]
@ineagu

**Comment by ineagu** [comment]
Great
