### ISSUE TITLE
Review JS for frontend

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#524]
We need to review the JS that we use in the frontend for maximum performance. 

Things that we need to review: 

- [x] Enqueue all JS from frontend in footer (!)
- [x] #531
- [x] Make sure the JS files are minified and loaded if and only if the block that requires them is used in the current page. 
- [x] Make sure to review the JS and it works with async behavior, i.e we don't check DOM before being ready, etc. Test it on slow connections Chrome network throttle features for something like Slow 3G.

**Comment by selul** [comment]
Seems like there is still room for improvements here. On a stock install, we load 100KB of JS even though nothing from Otter is used. 

We need to put more effort into this and code things carefully and with performance in mind.

**Comment by Soare-Robert-Daniel** [comment]
## Some ideas to discuss 

One is to save some metadata for the page:

- `hasCount`
- `hasTyping`
- `hasForm`

This will require an observer on the editor to check if everything is fine, and it will be fast on rendering. There might be some problems with FSE - Template Parts blocks since they are modular -- this is an important pain point.

Another option is to integrate into the already pipeline which parses the block and checks for CSS classes. It might be slower based on the search -- but still a problem with FSE.

**Comment by Soare-Robert-Daniel** [comment]
A fined tuned search for CSS in the content can do a good job, but we will need a good benchmark to prove it.

**Comment by selul** [comment]
@Soare-Robert-Daniel it might be some confusion on what we need for frontend vs editor context.

For instance, I see that we require a hooks JS file in the frontend when this is only required in the editor context. This is just one example.  
 
Loading JS files in the footer also allow them to be enqueued only when the block is rendered, i.e connected to the render filter or similar.

**Comment by HardeepAsrani** [comment]
We don't need to use multiple metadata but one that can have that. We also need to make sure that it is backward compatible. Hence we add a meta field, even an empty object if there's nothing. And if the meta field doesn't exist, we add an empty on the first-page load.

**Comment by HardeepAsrani** [comment]
All was done here, only thing left was to stop the module CSS/JS from loading, I've opened a separate ticket for it: https://github.com/Codeinwp/otter-blocks/issues/927
