### ISSUE TITLE
Test Otter 1.1.5 Version

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#53]
This one is a little urgent as we've fixed some horrible bugs in 1.1.5 which can affect many users, so please put this in your priority while testing. I've tested from my side but you guys are amazing at finding ways to break Otter which is exactly what we need.

As a reminder, please make a site with the current version of Otter and add few templates and blocks in few pages so you can test with new version to see if they don't break.

Download the zip: https://drive.google.com/file/d/1W4u8xlgQm6F6A-_rHIYWo13ImdvUNvNp/view?usp=sharing

Here are the changes we've made, in which some have been tested already but it's always good to double check:

- Fix Button Group error in WP debug.log when no buttons are added.
- Redesigned Template Library, so use responsive sizes and see if you can find any flaws.
- Dynamic Column Resizing
- Fixed issue which didn't allow non-editors to use Section block properly. Try from an author and contributor account to check if it works properly.
- Added an option to Auto Display columns on Pages, which is inside the right menu of Gutenberg, where you can enable full screen and other options. Make sure only admins are able to mess with this option.

Also below two which needs to be tested the most:

- Fixed an issue with Button Group which was causing old Button Groups to fail after being published.
- Added Hover and Link control to Font Awesome block.

@radu-themeisle @stefan-cotitosu 

Let me know if you find all these are working so we could release the plugin. Gutenberg is painful (almost done with my life), and our aim is to make sure only we have to suffer from this pain, not the end users. 😄

**Comment by radu-themeisle** [comment]
- Current Button Group crashed after update, I'm using Local, but this happened on all the pages using that block http://prntscr.com/mswt1h
http://prntscr.com/mswtmh
http://prntscr.com/mswu2y

If I add now a Button Group there are no issues: http://prntscr.com/mswv2w


- Font Awesome links: using "#" to simulate a link doesn't work. A use case for it would be linking in the same page to the ID of another section, now it doesn't work.

- Redesigned Template Library: everything is ok

- Dynamic Column Resizing: everything is ok

- issue which didn't allow non-editors to use Section block properly: everything is ok

- option to Auto Display columns on Pages: I don't understand this option, nor I can find it. Can you share a screenshot with it?

**Comment by HardeepAsrani** [comment]
You'll find it here:

![mar-05-2019 03-08-59](https://user-images.githubusercontent.com/2649903/53764724-106c8300-3ef4-11e9-8a85-a4752c2ab769.gif)

@radu-themeisle

**Comment by HardeepAsrani** [comment]
Also, do we need an option to open links in new page for Icons? @radu-themeisle

**Comment by HardeepAsrani** [comment]
@radu-themeisle I'm not able to get my previous Buttons to fail with the new version. Can you make a site here that you used for local setup with the current version here: http://jurassic.ninja/

I'll try to install the latest version and see if it breaks.

Once @stefan-cotitosu tests then it will be easier to reproduce.

**Comment by HardeepAsrani** [comment]
Also, in your local version, can you try to reproduce it with Twenty Nineteen too?

**Comment by HardeepAsrani** [comment]
New link with fixes: https://drive.google.com/file/d/1W4u8xlgQm6F6A-_rHIYWo13ImdvUNvNp/view?usp=sharing @radu-themeisle 

Few notes:

- Try to see the issue with 5.0, like you did this time, and then 5.1
- Options won't be available in 5.0

Here's how you can change WP versions back and forth: https://wordpress.org/plugins/wp-downgrade/

Let me know how it goes. :)

**Comment by HardeepAsrani** [comment]
PS: Thanks for the review and help in figuring out the issue with 5.0 as that's a big one.

**Comment by stefan-cotitosu** [comment]
Looks nice, I like the Template Library enhancements (Author, Templates Coming Soon, no more preview button). I tried it from iPad and mobile and looks good 👍 

- Advanced Heading alignment works differently when editing the page from iPad; 
I've added an Advanced Heading block, and set the center alignment for Desktop only (left unset for mobile devices). If I check the page from iPad or mobile, the text is centered, it takes the Desktop setting. By editing the page from iPad the text is on aligned left.
- Dynamic Columns Resize - if you drag it very slowly, it shows 25% 26% 50% with 3 columns for a small interval. This would be 101%, but if you check the columns width in inspector it works properly, all values have 99.99%, probably it's not an issue, just the preview value seem to be wrong.
![image](https://user-images.githubusercontent.com/26867648/53825506-1b202a00-3f7f-11e9-9cda-4d741ce56e9e.png), otherwise it's ok

- About author block - image look weird in some cases
- Sharing Icons - maybe we can replace Google Plus with Instagram
![image](https://user-images.githubusercontent.com/26867648/53826323-093f8680-3f81-11e9-83c0-4ecb77d91280.png)
- Maybe align sharing icons one per row on mobile
![image](https://user-images.githubusercontent.com/26867648/53826388-2b390900-3f81-11e9-9ec9-8676e1a9a0cb.png)

- I don't understand how to enable this
``` Added an option to Auto Display columns on Pages ```
I've clicked it in the menu, then a pop-up asking to make section block the default block for pages appeared, checked the box and then nothing happened.

- Font Awesome icon color on hover is not working for me on front-end. On hover, it takes the color from the normal state. It works in the editor preview.
- Font Awesome link - I can use # or any external link, but can't scroll to an id in the page. Can we have an option to open the link in a new tab? 🙂 

For testing, I used Neve 2.0.0 and WP 5.1

**Comment by HardeepAsrani** [comment]
> Advanced Heading alignment works differently when editing the page from iPad;
> I've added an Advanced Heading block, and set the center alignment for Desktop only (left unset for mobile devices). If I check the page from iPad or mobile, the text is centered, it takes the Desktop setting. By editing the page from iPad the text is on aligned left.

The alignment is based on the device you're using. If you use a mobile, it will show you the alignment of the mobile. If I'm misunderstanding the issue then can you explain with a video (with voice)?

> Dynamic Columns Resize - if you drag it very slowly, it shows 25% 26% 50% with 3 columns for a small interval. This would be 101%, but if you check the columns width in inspector it works properly, all values have 99.99%, probably it's not an issue, just the preview value seem to be wrong.

Yea, just JavaScript rounding the numbers. 😄 

> About author block - image look weird in some cases

Theme styles. Can't do much about it now.

> Sharing Icons - maybe we can replace Google Plus with Instagram

It's sharing icons so we can't replace with Instagram. But as you suggested, we might have to remove Google Plus if it's being closed.

> Maybe align sharing icons one per row on mobile

It's really made to be used in the bottom of the post for sharing icons so don't need to align that way.

> Font Awesome icon color on hover is not working for me on front-end. On hover, it takes the color from the normal state. It works in the editor preview.

Yea, seems like a bug. Will have to see.

>  Font Awesome block crashed on update from Otter 1.1.4 to 1.1.5

Can you help in reproducing this issue?

**Comment by radu-themeisle** [comment]
Button Group:
- Rolling back to 1.1.4 invalidates them: http://prntscr.com/muz5pr
- Downgrading WP from 5.1 to 5.0 also invalidates them: http://prntscr.com/muz7u8
- WP 5.0 + update to Otter 1.1.5 works fine ✔

Font Awesome:
- It didn't crash on updating to 1.1.5 but it does give a validation warning in the console in the editor (on the front end there are no warnings): http://prntscr.com/muzcj8
- It looks like updating the page removes the validation error: http://prntscr.com/muzdjg
- Icon color on hover works for me (WP v 5.0 & 5.1): http://prntscr.com/muze35

**Comment by HardeepAsrani** [comment]
@radu-themeisle Thanks. Just for future ref, every time a block validates, even if successfully, Gutenberg shows the invalidation in the console, so it's not always an error but an indicator of the block being deprecated successfully.
