### ISSUE TITLE
Plugin Card Horizontal Style

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#551]
Plugin Card block needs to have a horizontal style. The design was made by Hitanshu.

![image](https://user-images.githubusercontent.com/2649903/80891748-cf345680-8ce3-11ea-86d1-fa7e6b9a44d3.png)

Button : #5C67B9
Background: #EBEBEB
Text: #333333
Label: #4F4F4F

**Comment by HardeepAsrani** [comment]
Just something extra, not important if we don't do it.

**Comment by arinaturcu** [comment]
@HardeepAsrani Do you think it would be a good idea to make the style of the existing card look more like the one designed by Hitanshu?
For example, have the same style for the download bottom and the same font family.

**Comment by HardeepAsrani** [comment]
What do you think @mghenciu?

**Comment by mghenciu** [comment]
Actually this is one of the blocks I tested recently, and this looks to be a snowflake block (specific, rarely used).
So as mentioned in [Notion](https://www.notion.so/themeisle/Plugin-Card-76da7e0845a741f7970272c85c5569be), and based on how this is used on Themeisle & Codeinwp blogs - definitely a Horizontal variation would help.

**Comment by HardeepAsrani** [comment]
@arinaturcu If you haven't started working on this then it might be good to wait as Mihai said he will do some tests and let us know if this design will be fit for some use-cases or if it will need some changes.

**Comment by JohnPixle** [comment]
@HardeepAsrani @mghenciu I did some rough mockups on the plugin card, for vertical and horizontal variants.
Let me know your input here so I can perhaps adjust some of the info displayed.

[Figma link](https://www.figma.com/file/oUhBapLheKEDbkbu31tpyu/Otter-Blocks-%26-Patterns?node-id=377%3A2519)

![Plugin card](https://user-images.githubusercontent.com/4193672/163788557-eb503450-703f-4804-8a2a-cb6d8f6d60b1.png)

I don't know if it's worth to add a couple of settings for each variant, like
- display rating
- display description
- display logo
- display header image

Thanks!

**Comment by mghenciu** [comment]
Nice work, @JohnPixle !
I think it's a very good direction.

A few things I would keep in mind:
- I would work the layout Cover, based on the current **default Plugin Image zise, which is** **772x250px**. This means that the max-width is 772px. This way we'll make sure the cover looks good, and nothing is cut out.
 ___
- for the things to hide/show, as you mentioned them - I would leave on the ones that are required by default from Wordpress, and look ok in any state (description, logo, installs). And **I would make **hide-able** the description, cover & rating**.
And that's because sometimes users may want to hide the description, for example how we do on [codeinwp blog](https://www.codeinwp.com/blog/best-wordpress-plugins/), or [Ti blog](https://themeisle.com/blog/amazon-affiliate-plugins/).
Made an example [in Figma for this](https://www.figma.com/file/oUhBapLheKEDbkbu31tpyu/Otter-Blocks-%26-Patterns?node-id=381%3A2628)
![image](https://user-images.githubusercontent.com/52494172/163818241-985c5b27-357a-40f7-8d18-2687a5a287d5.png)
___
- for the Card layout, I think we should keep in mind that there are plugin with multiple authors or with longer names. So I would suggest to keep things in one row, and this way we can fit at least one name:
![Screenshot 2022-04-18 at 17 12 43](https://user-images.githubusercontent.com/52494172/163820589-af3efa2a-704d-4e11-bf95-438e9471f91d.png)

___
- now regarding the informations to display in the Card, **I think 3 sections is a good number**. In terms of what exactly to show there, we can brainstorm more cc. @HardeepAsrani . For me the nr of Active installations, Last updated & WordPress Version, are the most important things. And for example the version number - doesn't matter for me.

We could also have more options, and let the users choose which 3 informations they want to display, which sounds nice - but it's a complex solution (and based on the fact that this Block is very specific, I am not sure that all the work would be worth it). 
___

- [ ] Also, for who will work on this task, please make sure to fix the Search-box visual cues.
As [mentioned in Notion](https://www.notion.so/themeisle/Plugin-Card-will-have-a-redesign-76da7e0845a741f7970272c85c5569be#0b8e755d8010401bbd762579d432da95), we can either just change the copy - making sure **users understand that they need to Hit Enter for search**. Or we can add a search/magnifying glass icon - as a search button:
![image](https://user-images.githubusercontent.com/52494172/163814402-19e6924f-a635-4180-9c48-cd2605ff7595.png)

**Comment by HardeepAsrani** [comment]
I think this block might be very niche and we should deprecate it unless we use it on our own websites. Do we use this block anywhere @carlosinho @milicavs on any of our blogs?

cc @mghenciu @JohnPixle

**Comment by ineagu** [comment]
I am not sure if we use the blog or the plugin card plugin. The block idea is not bad, maybe we can have it in a separated free plugin for the community, but I agree is not a general stuff for website building and rather confusing for the general public that don't write about wp

**Comment by HardeepAsrani** [comment]
@ineagu I don't see us doing something special that an existing plugin doesn't do already, so don't see it really providing any value other than at first when it was the only block plugin-card. Plus, it doesn't work with Themes so other plugins out there support both and someone needing this will probably want Themes as well.
