### ISSUE TITLE
Gallery block duplicates images when uploading new files

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/otter-blocks#677]
@HardeepAsrani If this plugin is active on a site and we upload images to create a gallery using gallery block, the images get duplicated with “-1” suffix.
1. Create a post (or just edit the existing one)
2. Add gallery block
3. Upload new pictures (do not choose from existing ones)
4. You will see pictures are being processed.
5. Save post
6. Go to the Media library… you should see your newly uploaded images duplicated.

https://wordpress.org/support/topic/gallery-block-duplicates-images-when-uploading-new-files/

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, can you replicate it? I can not reproduce the issue on my end.

**Comment by poonam279** [comment]
@Soare-Robert-Daniel, I have a test instance where you can replicate the issue.
 Admin area URL: https://bitesizedegg.tastewp.com/wp-admin 
 Username: poonam 
 Password: hUeDfmhZ3sU

**Comment by Soare-Robert-Daniel** [comment]
Thanks @poonam279.

@HardeepAsrani   This problem appears for Gallery because of the Masonry plugin extension. When uploading a single picture, the initialization of the Masonry might re-trigger the request. You can observe in the network panel that the block make two requests like this: http://otter.local/wp-json/wp/v2/media?_locale=user

<img width="1106" alt="Screenshot 2022-01-07 at 13 06 07" src="https://user-images.githubusercontent.com/17597852/148535288-4acd2324-cd5c-4b9d-af8a-b072aaf3bf1b.png">

Disabling this solve this problem https://github.com/Codeinwp/otter-blocks/blob/09a80537db8a5232f1bfcfa3e05d8c1793a1e613/src/blocks/plugins/masonry-extension/index.js#L51
