### ISSUE TITLE
Test 2.0.0

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#70]
We have a new release which we will push as soon as this testing completed. Once again, Otter General @radu-themeisle and @stefan-cotitosu, I need your help.

As always, I made a video to show you the major features so you can understand better.

Download Link: https://drive.google.com/file/d/1Waa9xpP-E3kxEZ1ITf113FsgMkjZ21ke/view?usp=sharing

Video Guide: https://www.loom.com/share/68f79eba7a2e4fa986e01a19755a45fc

Things to test:

- [ ] Test Google Map Block
- [ ] Test Post Grid Block
- [ ] Test to make sure Template Import is working
- [ ] Make sure Otter's Settings page is working. It should appear as soon as you activate the new version.
- [ ] Make sure the "Tour" only appears once and not each time you open the page.
- [ ] Make sure the redirection is working just fine and only once.
- [ ] Make sure the CSS Module is working good.
- [ ] Test to see if Otter now works with https://wordpress.org/plugins/product-blocks-for-woocommerce/
- [ ] Test Otter with WordPress 5.2 Beta: https://github.com/Codeinwp/gutenberg-blocks/issues/86

Let me know if you have any questions.

**Comment by radu-themeisle** [comment]
- **Onboarding prompt**: http://prntscr.com/nc6w80
What I believe can be improved: Black background overlay (like the one after the prompt when you have the tips), center the box, buttons and text, add Otter logo to title. Here's a sketch: https://www.dropbox.com/s/87s6dewnqawrl9v/Otter-welcome.jpg?dl=0
Make borders round, like the ones from the next steps: http://prntscr.com/nc7fja (I'd also make the borders rounded for the blocks: http://prntscr.com/nc7gov)
**I think we can actually remove this step as it kind of repeats the same idea in the next step which I consider looks better and user can choose to skip.**

I see that the solution you used for the Onboarding has a nice interface and if you press "x" it leaves a marker so you can pick up from where you were. It would be a better experience for users to pickup where they left.

- **Howdie, I'm Ollie** (lol, it's actually "Howdy", good we have autocorrect 😂):
Underline "skip" so that it better indicates in can be clicked: http://prntscr.com/nc7h9o ;
Shouldn't the buttons have a hover effect? (They should if they don't already have)
We can decide to use either "x" or skip, both are too much and they take up space: http://prntscr.com/nc7kgi ; I'd personally drop "skip" and use the "x" with rounded border like in my example, it will make the box less crowded.
**_Here's a sketch:_** http://prntscr.com/nc7sci

- **Custom CSS**: change text to "Jazz up your blocks with some sparkly custom CSS right inside the block." http://prntscr.com/nc83cf

**You can use this general styling for the tips content:**
```
font-size: 1.4em;
line-height: 1.5em;
text-align: center;
```

- **Section**: change the text a bit and center the box and arrow. Is it block with a capital b or not? In the tip it's with capital, in the settings it's without. You should check that it's spelled the same everywhere.
**_Here's a sketch:_** http://prntscr.com/nc88vi

- **Maps**: just a small content change: http://prntscr.com/nc8q82

- **API key**: small change: http://prntscr.com/nc8tkb
Wouldn't it be better to have the link point directly to where you can generate the key? https://console.cloud.google.com/google/maps-apis/

- **Ask a question**: just the font styling and move the arrow beneath the "ask a question button" so it point directly to it.

- **Leave a review**: Here I'd avoid using "leave a good review" just use "review". It sounds like we're needy and want a good review. My approach would be just to encourage leaving a review because it shows they like what we do and I'd write on the button "Review Otter".

- **That's it for now!**: Let's move it down on the Otter icon, it's not a good practice to come back to a previous place that we've already been. There's a typo at "Hope you enjoying..." it's "Hope you enjoy..." but I'd write this instead: "We hope you'll enjoy and love Otter as much as we do"; because this is the first and only time they'll see these tips.
Here's a sketch: https://www.dropbox.com/s/7byanbzqxksizpr/Otter-finish.jpg?dl=0

- **Love this** 👉 http://prntscr.com/nc967d 😍

Tomorrow I'll come back with the test results for functionalities, bugs, WP beta version etc.

**Comment by radu-themeisle** [comment]
- **Test Google Map Block**:
Custom CSS doesn't work: [before](http://prntscr.com/ncl9tp), [front](http://prntscr.com/ncl9bu), [after](http://prntscr.com/ncl9kk)
Check if this class is added or is it from jurassic.ninja: http://prntscr.com/nclmfc
Updating from the current version works fine.

- **Test Post Grid Block**
Custom CSS doesn't work: [before](http://prntscr.com/ncm0hp), [front](http://prntscr.com/nclynp), [after](http://prntscr.com/nclzg7)
Updating from the current version works fine.

- **Test to make sure Template Import is working**:
Got an error for the Neve Original Latest Blog template: http://prntscr.com/ncm9a8 Adding a new one works just fine, so I guess some template blocks will need to be updated.

- **Make sure Otter's Settings page is working; Make sure the "Tour" only appears once and not each time you open the page;   Make sure the redirection is working just fine and only once** ✔

- **Make sure the CSS Module is working good**: as I previously mentioned for me the custom CSS doesn't work as once I save and go to view the page it's gone and when coming back to the editor the CSS is gone. This happens regardless of the block used. For testing I had only Otter enabled,  twentyseventeen and Neve.

- **Full Screen mode**: Nice but remove the [keyboard shortcut](http://prntscr.com/ncnimt) because it triggers the browser's search function, plus I don't believe users are not generally using keyboard shortcuts (maybe some of the advanced ones) so a button is enough for now.

- **Test to see if Otter now works with Product Blocks for WooCommerce**: I'm not sure what should we test here and I don't understand why we are worried about compatibility with a +300 installs plugin, we should worry about plugins with thousands of installs.

- **Test Otter with WordPress 5.2 Beta**:
_Advanced Heading_: Looks like there might be some issues with line-height: [editor view](http://prntscr.com/ncoc1l), [front view](http://prntscr.com/ncobnw)
So it seems the issue comes from not having a line-height set, if you set it than all the lines have the correct line-height. But if you delete the value (like trying to [reset to the default](http://prntscr.com/ncof80)) then it seems the block uses the "[last known](http://prntscr.com/ncoezl)" value, the one that you deleted instead of reverting to the default. This might not be actually related to the beta version.
_Pricing block_: the separators are [not centered in the editor](http://prntscr.com/ncos9x), on the front they look ok.
_About author_: just [keeps loading](http://prntscr.com/ncoswf) but on the front it shows. Going back to the editor it' still loading.
_Font Awesome Icon_: hover colors don't work properly: [editor](http://prntscr.com/ncoulz) vs [front](http://prntscr.com/ncov43).
_Plugin card_: aligning to center doesn't work on the [front](http://prntscr.com/ncowaf), it works in the [editor](http://prntscr.com/ncowz1)
_Sharing icons_: not vertically aligned on the [front](http://prntscr.com/ncoxm4), editor [looks ok](http://prntscr.com/ncoy1p).
_Testimonial_: If you change the colors of the advanced headings they [change their font](https://www.loom.com/share/13588444ca614deca7c142bf382de75a)
