### ISSUE TITLE
Section and other bloc types broken in 1.7.5

### ISSUE THREAD

**Issue by seleborg** [Codeinwp/otter-blocks#720]
This is a rather urgent issue, as it seems **editing Otter blocks no longer works** with the newly released 1.7.5.

Observed (local dev machine and live product server):

- In the WordPress (Gutenberg) editor, Section blocks are no longer editable. WordPress displays a warning that the block type "themeisle-blocks/advanced-columns" is not supported (see screenshot from a German installation).
- In the blocks browser, the only available block type by Otter is the Masonry block.
- Pages still display fine on the live website.
![image](https://user-images.githubusercontent.com/6088810/153053781-3450edf3-d450-48af-aa87-7211ec3b9144.png)

Expected:
- Blocks editable as usual.

Steps to reproduce (tried on my machine):
- Ensure versions WordPress version 5.8.3 OR 5.9 and Otter v. 1.7.4
- Edit a page with a Section block inside -> Works as expected.
- Update plugin to Otter v.175
- Edit same page as above -> Section block not editable, displays warning as described above.

**Comment by HardeepAsrani** [comment]
Hey @seleborg,

Thank you for creating an issue. We have tried and weren't able to reproduce this, been trying since morning. Would it be possible for you to reproduce this issue here for us to check? https://tastewp.com/ - once you've reproduced it, you can  share the credentials here with us.

That website allows you to create a testing WP instance with just one click.

**Comment by seleborg** [comment]
I'll give it a show, though tastewp.com doesn't seem to load for me ATM. I'll keep you posted.

On my local machine, I tried disabling all plugins except Otter but the bug remains. 

My hunch would be a stale file from a previous version lurching around, which you wouldn't have on your (likely) pristine dev setups, but that's just my uninformed guess.

**Comment by HardeepAsrani** [comment]
@seleborg That shouldn't happen as the files that we serve are made automatically during the release process. That should've also broken the new installs.

Would it be possible for you to add us as admin on your website if you're comfortable with that? If you are then we can take this chat to email.

**Comment by seleborg** [comment]
Let's get together over email. How do I reach you?

**Comment by HardeepAsrani** [comment]
@seleborg you can send an email at hardeep@themeisle.com

**Comment by HardeepAsrani** [comment]
Note for future reference: after debugging with the help of @seleborg, it turned out to be just browser cache, even tho scripts of each release are loaded with unique version arguments to force reloading.

I'll keep the issue open for now until we stop getting more support tickets in case we find anything new.
