### ISSUE TITLE
Copy Paste Styles

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#776]
Originally slated for 2.0, Copy/Paste Styles from one block to another, should be available for Otter + Core blocks, import media items on paste

**Comment by HardeepAsrani** [comment]
We can decide some styles each block (Otter ones) that people can click on Copy Styles from this menu:
<img width="719" alt="Screenshot 2022-03-08 at 4 32 58 PM" src="https://user-images.githubusercontent.com/2649903/157225976-6eb6760b-e7d4-4784-9303-0474aac8092a.png">
 
And on the same block type, they can just Paste Styles and those things will be taken. It can be just all the colors for all the blocks.

**Comment by HardeepAsrani** [comment]
I did some research for this yesterday and here's what we can do about Copy/Paste styles:

- For the Core styles, it will be hard to pick what attributes to pick as they will vary between different versions of Gutenberg but a good way will be to pick the ones that are added to Core Blocks using block supports as that makes sure that the name of the attribute will be same throughout the editor.

These include:

- Background
- Text Color
- Link Color
- Typography
- Margin
- Padding

These values we can copy and paste between all the blocks based on if the blocks support it.

- For the Otter Blocks, we can simply define which attribute we want to be able to copy/paste and rename them to some standard name. Instead of, for example, "frontColor," we can rename it to Primary color (for the copy/paste reference, not the name of the attribute) so it can be shared between all Otter blocks where the attributes have the same reference.

If the user is copy/pasting between the same type of block (of Otter) then we can copy/paste all the styling-related attributes. I will mostly limit these to Colors/Typography and not copy.

This feature is similar to: https://elementor.com/blog/introducing-copy-paste/

So my question for @JohnPixle @mghenciu is, do you think we should only copy-paste Colors/Typography (as they can be used between most of the things) rather than Padding/Margin/Spacing and such?

What do you think?

**Comment by JohnPixle** [comment]
Hey @HardeepAsrani as a user I would definitely expect to copy all style-related information, so apart from typography I would also go with the others you mentioned plus border styles. This is essentially how it works with elementor.

We should keep in mind that since we will provide plain / fill / border styles for most of the blocks, we need to provide the related UI controls to facilitate these styles. So in most of the blocks we should have the border property as well. 

>  Instead of, for example, "frontColor," we can rename it to Primary color (for the copy/paste reference, not the name of the attribute) so it can be shared between all Otter blocks where the attributes have the same reference.

Absolutely. We need to start embracing this logic I believe and refer to colors etc based on their role in the design. Open to your suggestions, let us know what would work.

**Comment by HardeepAsrani** [comment]
@JohnPixle Good point, Elementor does that - I thought they didn't. It will be a little hard to do but we can try and see how it goes.

**Comment by mghenciu** [comment]
I don't have technical evidence for this, but from working with Elementor and from testing it now, it looks like the Pate Style has effects only on the **blocks from the same Type**.

So for example I can Copy the Style from a Button widget, and paste the same Style on another button widget.
But after I Copy the Style (from the button), I can also click on any other widget - I will still have the option to Paste Style, but **that won't do anything**, because the widgets are a different type.

___
This won't work even with text widgets, that may look similar. So for example if I copy the Style from a Heading - **I can't** paste it over a Paragraph (even if in theory we can say that those can share Typography settings).

___
And I think this is a good practice, avoiding conflicts when pasting.
In Gutenberg/Otter case, there is also the option to Convert a block to something else (for example an Advanced Heading to a Paragraph), and that's a bit tricky (I guess).

But overall I think **it's safe to assume that Copy Past should work only on the blocks with the same Type**.

**Comment by JohnPixle** [comment]
@mghenciu Yes, this is exactly as it goes in Elementor. I suggest we can have it for **the same type of blocks** as well.

**Comment by HardeepAsrani** [comment]
But I think we can have some options to copy/paste across the blocks, like typography, background, and content color which are part of Code's Support mechanism. We don't use that mechanism because it was introduced later so it will be hell to migrate but that will give us a good understanding to migrate those values for most things.

**Comment by JohnPixle** [comment]
@HardeepAsrani perhaps apart from typography, background and content color, we could see if the core mechanism supports things like padding and borders? Assuming that these controls will be consistent to (almost) all of our blocks.

**Comment by JohnPixle** [comment]
Ah, I see you mention in your earlier comment which properties are supported, thanks!

- Background
- Text Color
- Link Color
- Typography
- Margin
- Padding

**Comment by Soare-Robert-Daniel** [comment]
## Idea # 1

When you press on the block `Options`, you will have the `Copy Style` button.


<img width="250" src="https://user-images.githubusercontent.com/17597852/189332975-9c59c47d-e5b6-4e7d-90cd-9c0f70801ddd.png" />

When you press, we copy all styling attributes that include names like: `padding`, `margin`, `align`, `color`, `width`, `height`, etc.

`Column Block` attributes: 

https://github.com/Codeinwp/otter-blocks/blob/092deb9c32c31975792617f1e66b9d5526b6d356/src/blocks/blocks/section/column/block.json#L14-L105

Then, you select another same type block, and the in the `Options` you will have a `Paste Style`

<img width="250" src="https://user-images.githubusercontent.com/17597852/189333598-cffdc211-ef8a-4363-8e12-1c59bec412cc.png" />

@HardeepAsrani, is this how you imagined working?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, do you think is worth having a Copy Paste History?

When you copy a style, it is saved in a list on a global object, then we have a button in this menu:

![image](https://user-images.githubusercontent.com/17597852/189341817-627d87e3-ac9b-47c4-8056-0fd21c97c710.png)

When clicked, it will show a small window with the History.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We don't need history.

And the mechanism for copy/pasting is pretty easy, what we need to do is first set a standard of how we approach this. If multiple blocks are selected, we copy all of them, same goes with pasting. And where exactly we save copy data. In the browser storage? In the system's copy history?

And to have some sort of standard mapping where, for example, we save margins to some attribute name margin, even if block's margin attribute's name is "mainMargin."
