### ISSUE TITLE
Advanced Heading - enhancements

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#823]
- [ ] Transition the Typography settings form what we have no, to Core wp 5.9.
Currently in Advanced Heading Block for example, we have a number of typography settings that can be replaced with Core Controls. If this is not possible yet, we can at least add Relative units for the Typography controls (font-size, line-height).
![image](https://user-images.githubusercontent.com/52494172/158995830-3ed733d8-25a8-415d-8ddd-30b123de1d9f.png)

### This is the core Heading Block where it has all the typographic options inside a panel.
![image](https://user-images.githubusercontent.com/52494172/158995930-ae5fb325-8b70-4e9d-b0dc-69a1b1b58025.png)

___

**Comment by JohnPixle** [comment]
After some friction with the Advanced heading block, I have a couple of things to add:

### 1. Font Style dropdown: Bold weight
Currently, the only available font styles are normal and italics. We need to add a bold weight in there (600). So far we are relying on the block toolbar to add a bold weight, but this is actually a fake bold that the browser applies. It is not the same as having a 600 font weight (Which is the original bold weight defined by the font).

### 2. Font Shadow works only with custom colors (not vars)
If I select any of the colors in the theme color palette (Neve), it does not apply on the shadow. It only works if I use a custom color.

I believe this might be expected behaviour with color variables, but if this is the case, we should remove the theme palette from there. 

![Screenshot 2022-05-11 at 14 39 15](https://user-images.githubusercontent.com/4193672/167841191-af71b251-1808-4fe5-a7bc-2b769b8ed87e.png)

Will keep adding more feedback If I have any.

**Comment by HardeepAsrani** [comment]
Noting down another:

- Google Fonts don't work on iFrame in the editor.

**Comment by HardeepAsrani** [comment]
@JohnPixle It's part of that issue but we couldn't fix it in it. It was the only thing left so didn't want to hold that PR just for one issue.

**Comment by mghenciu** [comment]
- [ ] Lets add **Alignment options** in the Toolbar, for the Advanced heading block:
<img width="498" alt="Screenshot 2022-08-22 at 16 24 59" src="https://user-images.githubusercontent.com/52494172/185932091-42a28cc8-c339-4fd9-bd3a-6ddbe829be82.png">

**Comment by mghenciu** [comment]
> @mghenciu It's not added in the toolbar because of the responsive controls. One idea would be to show the controls for the currently selected device mode...however it can be confusing for the users. What do you think?

**If we can show there the value based on Device, I think it should be fine.** Not sure how would this confuse users.

But for sure we need to make sure those are inherited/displayed correctly otherwise it will become confusing.
For example in this case it shows nothing, while **the Headline is aligned to the left**:
<img width="1722" alt="Screenshot 2022-08-23 at 11 40 45" src="https://user-images.githubusercontent.com/52494172/186113462-8d6991c3-7cae-4690-b18e-c715e9515466.png">

___
while with a Core Headline, the displayed Alignment Icon is the correct one:
<img width="1348" alt="Screenshot 2022-08-23 at 11 41 03" src="https://user-images.githubusercontent.com/52494172/186113589-aa5947cb-b4cb-40a9-9d8a-461460c0904f.png">
