### ISSUE TITLE
Description Tab missing when using Woo Product Builder

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#875]
As seen in the image, the product has 2 tabs:
<img width="1597" alt="Screenshot 2022-04-19 at 13 30 48" src="https://user-images.githubusercontent.com/52494172/163985587-61d2420c-be45-4b13-be28-7730719edd27.png">

When the Woo Product Builder is enabled, there is only 1 tab:
<img width="1704" alt="image" src="https://user-images.githubusercontent.com/52494172/163985711-72660dd7-538e-468e-8bfa-643c5b5288c0.png">
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/52494172/163985750-1961978d-86ee-4393-a803-6b1702ac9aaa.png">

Repro steps:
- Import this demo >> https://demosites.io/perfume-shop-gb/
- Enable Woocommerce Product Builder on a Product page
- Notice that the Description Tabs is not present

**Comment by HardeepAsrani** [comment]
@mghenciu it's actually not an issue. Usually whatever you put in the editor inside Woo, it all goes inside the description tab.

In Woo builder, the description tab is the main content where you use the block editor.

**Comment by mghenciu** [comment]
> @mghenciu it's actually not an issue. Usually whatever you put in the editor inside Woo, it all goes inside the description tab.
> 
> In Woo builder, the description tab is the main content where you use the block editor.

I am bit confused here.
What are you saying is that normally it should work similarly how it's described [here](https://youtu.be/xJnhrmjqhTA?t=189).

While when I tried using it, this is how a product page looked **before enabling Woocommerce Builder**:
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/52494172/164492394-28d28990-cd8e-43bf-9a88-f2622bdf6a33.png">
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/52494172/164492462-5c027d18-dd1a-430e-ac98-3b71ffa09f01.png">

___
and this is how it looks after I the **Woo Builder is enabled**:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/52494172/164493717-5d5098e6-0731-46d2-b21c-e13684b0bf68.png">


<img width="2555" alt="image" src="https://user-images.githubusercontent.com/52494172/164493371-713630e2-c095-4370-92d5-562c2eab6d27.png">


___
Now if we go for a similar approach, like the one in the video, where it would be possible to use Otter in the Description Area - then yes, not having the Description Tab makes sense.

But from what I've managed to achieve now, it looks more like a **Total rebuild of a Product page** using blocks. And in this case, all the tabs will be needed, including the description one.

Let me know if I missed something when enabling the Woo Builder.

**Comment by HardeepAsrani** [comment]
@mghenciu All the things that you add to the page (like any blocks to design the page) is actually added to the description of the page, so if we start showing the description tab then it will become a loop and things won't work. So that's why we can't show the description.

And the Short Description is a different field than the description. Maybe in future we can allow user to edit tab options and use the Short Description field in the Description.

Once we are done with Otter Pro, I've some ideas for Woo Builder, that includes:

- Give a couple of pre-built options for users to choose from.
- Allow user to just make one template and use it as a global one for all the blocks, it should be noted that this feature will sort of become irrelevant as Woo starts supporting FSE.
