### ISSUE TITLE
Inline color issue in Advanced heading block

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#909]
I think I spotted a weird issue regarding the default color of the advanced heading. It appears there is an inline style of #000000 somewhere that is creating this confusing issue. Please take a look at the video whenever you can, as it shows the exact behaviour.

Overall, it  would be good to drop any custom colors on text instances, in order to have a meaningful cascade from the theme styles. I am not sure if simply by removing the inline value #000000 will fix the issue, but it might definitely be a good idea.

https://www.loom.com/share/264ba5abb7ca4d12bae941d91b06bb2d

Thanks!

**Comment by Soare-Robert-Daniel** [comment]
@JohnPixle, this happens because the default color is black. The clear button removes any change in the color, but not the default one.

https://github.com/Codeinwp/otter-blocks/blob/eb02882e4c5bef2458ad3095f60d6ecdc7c5d8ef/src/blocks/blocks/advanced-heading/block.json#L33-L36

I think we can safely remove it.

**Comment by JohnPixle** [comment]
Awesome, many thanks!!
