### ISSUE TITLE
Countdown not working at the frontend (using Neve)

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#912]
I am having a strange issue with the countdown, when working on a Neve starter site.

While everything looks good in the editor, at the frontend the countdown is always zero.

### Editor

![Screenshot 2022-05-11 at 14 19 41](https://user-images.githubusercontent.com/4193672/167837573-774a4f4a-a9de-47dc-bbae-e8de4b3ab70b.png)

### Frontend

You can find the [live page here](https://demosites.io/nft-illustrator-gb/nfts/) if it helps.

![Screenshot 2022-05-11 at 14 19 51](https://user-images.githubusercontent.com/4193672/167837593-d9bb1828-930b-4c88-8123-b204dcf33c38.png)

I have to admit though that I tested it with the default theme and the countdown works as expected. Might be an issue with Neve worth looking into?

Thanks!

**Comment by Soare-Robert-Daniel** [comment]
I can not reproduce this. @HardeepAsrani, do you think it might be a cache issue?

**Comment by HardeepAsrani** [comment]
@JohnPixle I've fixed it on the website. You can try to import it somewhere to make sure it doesn't happen there.

@Soare-Robert-Daniel It seems the `name="day/hour/minute"` tag was being stripped from the Save function. Any idea in the code what can lead to do that, given you made that component?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani , we don't have such a thing. The `date` from the `DateTimePicker` is saved as it is in the Save function.

https://github.com/Codeinwp/otter-blocks/blob/398060a98fb8db9c9604c59a45308b18fa76c250/src/blocks/blocks/countdown/save.js#L66

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Problem is somewhere here: https://github.com/Codeinwp/otter-blocks/blob/398060a98fb8db9c9604c59a45308b18fa76c250/src/blocks/blocks/countdown/save.js#L46-L48

**Comment by HardeepAsrani** [comment]
@irinelenache When you have time, can you see if it's possible for you to reproduce an issue like this with Countdown block?

**Comment by irinelenache** [comment]
@HardeepAsrani I tried with a lot of settings, also imported some starter sites and i didn't manage to reproduce it

**Comment by HardeepAsrani** [comment]
@irinelenache Thanks for the trying.

@mghenciu @JohnPixle Do you ever try to edit the HTML directly? That could be one possible reasons as so far I don't see any issue with the code.

**Comment by mghenciu** [comment]
> @mghenciu @JohnPixle Do you ever try to edit the HTML directly? That could be one possible reasons as so far I don't see any issue with the code.

Not really, I mean we/I prefer to only use Blocks and not alter any code manually.

___
Here, the issue may be again only happening on demosites.io - and be something that can't be reproduced.
But I can confirm that when John asked me tot take a look on the demo, the Countdown wasn't working.

Repro steps just for you @HardeepAsrani , as you have acces to demosites:
1. As of today **May 17**, 2022, the Countdown on the Homepage doesn't work (this is how it looks in FE):
![image](https://user-images.githubusercontent.com/52494172/168849867-94b17eaf-a079-4f18-b1b7-7d303eea5f6f.png)

2. And this is the Backend:
![image](https://user-images.githubusercontent.com/52494172/168849977-5d5410b5-7100-4e00-9853-eef5920fac5f.png)

3. If I press Attempt Block Recovery, probably it would work - but on **May 13** (when John showed me the demo) I did the same Block Recovery to fix it, and it was working. What changed between this dates? a lot, I guess - as we released Otter Pro.

But this isn't happening for the first time. Maybe you remember @Soare-Robert-Daniel, I showed you in the office that this [Architecture Site](https://demosites.io/architecture-studio-gb/) - had the same problem with the Form blocks.

In **conclusion**, even if for us this may be not such a big issue (because we can recover the block) - I think it would help to know if this also happens to users, or it's just something on demosites.io.
___
On the same site and page, the Popup fields also don't work as expected:
![Screenshot 2022-05-17 at 18 32 25](https://user-images.githubusercontent.com/52494172/168850344-fb1a9c07-a013-4e46-b5d8-81bbf57d3b57.png)
![image](https://user-images.githubusercontent.com/52494172/168850413-908fbcca-efae-4fdb-bfe1-7743a34c14fe.png)

**Comment by JohnPixle** [comment]
@HardeepAsrani Nope, never edited html. It might just be one of these issues that are happening with demosites only 🤷🏻‍♂️, it works fine with the default wp theme as stated in the original comment. 

The countdown [on the demo](https://demosites.io/nft-illustrator-gb/nfts/) is still not working sadly.

![Screenshot 2022-05-17 at 18 41 32](https://user-images.githubusercontent.com/4193672/168852439-a17000f4-d876-45ac-a70d-c07f0c6122dc.png)
.

**Comment by JohnPixle** [comment]
@mghenciu we posted at the same time almost 🙃. 
Screenshots are from the same demo site, I am just working on the color palettes

I also tried using the countdown on a simple page at https://demosites.io/otter/countdown/ and still got nasty results.

**Comment by irinelenache** [comment]
@HardeepAsrani @mghenciu @JohnPixle 
I tried to create a wordpress multisite so maybe i could reproduce it, but still couldn't. Are there any other plugins/settings on demosites that can lead to this strange behaviour?

Also, you can try to reproduce it here and see if you get any result:
```
https://network.s.themeisle.com/test-site/wp-admin/
user: network
password: 5SKgUBO1
```

**Comment by irinelenache** [comment]
@HardeepAsrani I'll move this to Backlog as we weren't able to reproduce it 👍

**Comment by JohnPixle** [comment]
@irinelenache yeah, I guess it's ok. This block will need to go through a heavy re-work soon anyway, and we have another ticket where we gather information. Thanks!
