### ISSUE TITLE
Version 2.0.3 Known Issues

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#919]
- [x] Upsell link missing for Upsell table
- [x] Pro bundle files not skipped from build folder.

**Comment by Soare-Robert-Daniel** [comment]
- Investigate breaking style in Editor for Tabs in WP 6-RC1

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel You can put that here instead: https://github.com/Codeinwp/otter-blocks/issues/906

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani I updated Neve and Neve Pro on a site that I own and when trying to download Otter Pro from the notification I got this:
<img width="911" alt="Screenshot 2022-05-12 at 19 12 23" src="https://user-images.githubusercontent.com/9929553/168121193-888bb707-90fb-41da-a0ae-ffa16817a743.png">

**Comment by cristian-ungureanu** [comment]
I tried it on TasteWp and it worked there, but it installed v1.7.5 and it appears that there is an update but there isn't
<img width="1354" alt="Screenshot 2022-05-12 at 19 26 30" src="https://user-images.githubusercontent.com/9929553/168123548-66c693c1-2402-4384-9f50-c485ffcdc48c.png">

**Comment by selul** [comment]
@HardeepAsrani the version has not been updated in the otter-pro.php

**Comment by selul** [comment]
there is a bit of inconsistency inside the user flow:

- First of all all the links inside the plugin should be to the upgrade page. Right now is leading to first page where I have Free download pushed front which makes no sense since I’m going there from the free plugin, I already have the free plugin. I would recommend also to use a constant for all links for upgrade for easier management.
- This looks very crowded https://vertis.d.pr/5VkAZn, I would add some info icon or something more subtle for Disable in Otter settings, I see no point in having this in prim plan. Something more subtle with an info icon that shows that message would make more sense.
- The upsell orange message should be on single line: Maybe something Extend with more options -> https://vertis.d.pr/xZEH9U, now is taking too much space
- I feel like we have a lot more to do discover pro features, like showing the pro blocks with locked icon maybe? some toast like we had [here](https://user-images.githubusercontent.com/52494172/163560823-78072b74-fdb3-4709-9484-5abb5eead5ea.png).

What do you guys think?

**Comment by HardeepAsrani** [comment]
I've also synced the Comparison table content with this page: https://themeisle.com/plugins/otter-blocks/upgrade/

**Comment by HardeepAsrani** [comment]
> I feel like we have a lot more to do discover pro features, like showing the pro blocks with locked icon maybe? some toast like we had [here](https://user-images.githubusercontent.com/52494172/163560823-78072b74-fdb3-4709-9484-5abb5eead5ea.png).

We can try adding the toast but can't show the icons there, no way to make them locked.
