### ISSUE TITLE
Flags for loading module's CSS/Scripts in front

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#927]
We can have one meta key where we add all the Otter post info that we need that includes flags on which front-end script we should load + we can also merge the already existence has_review meta to this.

`_otter_meta` or something

**Comment by Soare-Robert-Daniel** [comment]
The problem with this is the FSE. If you make an animated block in the Header template part, it will not have a meta key since it is not a post or a page.

Very hard to find an elegant solution for this probem.

**Comment by Soare-Robert-Daniel** [comment]
A possible solution is to build an in-memory cache.

If someone requests for the first time the page, all the parsing for detecting the loading scripts will be done, then we save what scripts were loaded for that request in a dictionary. And next time, we look it up in the dictionary.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel But can we at least do it for non FSE pages?

**Comment by Soare-Robert-Daniel** [comment]
No idea about it. I only thought about the posts and pages.

**Comment by selul** [comment]
hi there, 

How about if we save it in the post_meta when sticky/animation is added, like a callback, and when the post is rendered we enqueue those automatically based on the meta? 

For legacy websites, not sure if we can parse when they are editing the page and set that meta for post already created? 

Also for sticky, we can add a global toggle to turn this off as we do on animation since this can be a good method to turn the scripts off from loading. 

Both animations and sticky should be loaded in the footer to prevent render-blocking behavior. 

> A possible solution is to build an in-memory cache.

If you are talking about object cache, this is an opt-in service and most websites don't have it on their hosting.

**Comment by Soare-Robert-Daniel** [comment]
> How about if we save it in the post_meta when sticky/animation is added, like a callback, and when the post is rendered we enqueue those automatically based on the meta?

This will work for posts and pages. But not sure about Template Parts from FSE, which don't have an ID.

**Comment by selul** [comment]
in this has can't we add an attribute to the block when animation/sticky is used and hook to render_block to flag the style loading?

**Comment by Soare-Robert-Daniel** [comment]
> hook to render_block to flag the style loading?
This might be a good idea. But if I am not wrong, `render_blocks` is a filter, so we need to find how to make the loading aware of each other to not enqueue multiple times.

**Comment by selul** [comment]
this won't be a problem since the handles are unique, enqueuing the same handle multiple times will load it just once in the frontend.
