### ISSUE TITLE
Refresh Otter Blocks Icons

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#928]
As mentioned [here](https://github.com/Codeinwp/otter-blocks/issues/865), icons for Otter Blocks could look better.
Currently there are some inconsistency issue (having different stroke, size), but also there are a lot of Icons that look similar or the same.

**Comment by mghenciu** [comment]
@HardeepAsrani 
What do you think is the best approach for this? A complete overhaul for the Icons would probably take some time, so I am thinking **we ca do 1 minor round where we fix small inconsistencies** (for example the Form Block - attached)
![166651281-ff849c9d-e566-4c3f-bc92-f04ebfa4a55f](https://user-images.githubusercontent.com/52494172/168778245-e0e6d9b7-f7fd-49f8-a9a1-ad5c033fae82.svg)


, and in the **second round do a whole overhaul**.

cc. @JohnPixle

**Comment by JohnPixle** [comment]
Definitely agree on this, I personally believe that if we have the resources to do an overhaul of the icons, it is something we must do in this relatively early stage of the product. Competition on this is tough.

If Dragos can work on them, it would be awesome, because he will extend the same style into the new icons, which will make the transition easier for the users. 

There is also good existing material for references, so Dragos can get inspired on how others have approached similar concepts, and not need to conceptually re-create the wheel for each block.

**Comment by HardeepAsrani** [comment]
@JohnPixle When you get some time, can you collaborate with Andreea on this? I'm excited for custom icons. 😄

**Comment by JohnPixle** [comment]
@HardeepAsrani Sure thing, I will arrange it with her on Slack, she does not appear to have a Github profile as I see.

Will keep you posted!

**Comment by selul** [comment]
@JohnPixle she has -> @poorse02 , it's also in the @Codeinwp/design-team

**Comment by JohnPixle** [comment]
Hey @poorse02 !
So, regarding the Otter icons, just wanted to share some initial input so you can get started whenever you see fit.

Suggestion:
I would start by creating a clean WordPress setup, and installing the following Block-based plugins, so you can see how others have approached the icon design.

[Gutenberg Blocks by Kadence Blocks – Page Builder Features](https://wordpress.org/plugins/kadence-blocks/)
[Spectra – WordPress Gutenberg Blocks](https://wordpress.org/plugins/ultimate-addons-for-gutenberg/)
[GutenBee – Gutenberg Blocks](https://wordpress.org/plugins/gutenbee/)
[Stackable – Page Builder Gutenberg Blocks](https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/)
[Gutenberg Blocks by Kadence Blocks – Page Builder Features](https://wordpress.org/plugins/kadence-blocks/)

and of course:

[Otter – Page Builder Blocks & Extensions for Gutenberg](https://wordpress.org/plugins/otter-blocks/) where you can find all the existing Otter blocks, and their current icons.

![Iconsets](https://user-images.githubusercontent.com/4193672/174273858-6b68bb8f-c75f-4b25-978f-8135ae71eb2a.png)


No need to re-invent the wheel conceptually for each block, I believe we should focus on having a clean readable icon-set with consistent style and line widths. 

I will leave it up to you on how you will organise the workflow, I have never worked on icons before, so feel free to create a new Figma file and setup your workspace. Let me know if you need any help

Specs:
- The final format of the icons should be SVG
- The original size of each icon should be 24x24 px
- Icons should be single-colored. We can leave the color for the end, but it should be aligned with the Otter brand.

Let me know if you need any help! You may want to start with 5-6 icons initially, and as soon as we are set on the direction and style, you can proceed with the others.

John


PS: 

@HardeepAsrani  I saw that some of the icons in the block inserter sidebar are 24x24 but there are some others that are at 20x20. Can you confirm we are good to go with 24x24 ? I want to avoid resizing the icons in the final product. Let me know! 👍🏻 

cc @mghenciu

**Comment by HardeepAsrani** [comment]
@JohnPixle Yes, it should be 24x24. Many we used 20x20 when other alternatives weren't available.

**Comment by poorse02** [comment]
Hello everyone, I'm coming back with an update.
I've done some research, studied our icons and the competitor's and looked into what our features do and I've chosen, as a starting point, to redo 5 icons that I've considered that don't match their functionality or that could use an improvement more than the others, for now.

Here are the 5 icons I've chosen and their variants:
![image](https://user-images.githubusercontent.com/67728772/186392702-51986e74-323f-4471-ba42-40ecdc08a11b.png)

And here they are in a mockup:
![image](https://user-images.githubusercontent.com/67728772/186392838-1556f9aa-de76-4c52-99cd-4c6e307c6c55.png)

____
I've chosen to go with rounded corners to match the gentle/ playful nature of the logo and for readability reasons I've chosen to go with outline icons instead of solid ones because the spacing between elements of the icons would be limited in most cases. Perhaps there could be some leeway to have one element of the icon filled, if it makes sense and it doesn't break the consistency of the set (e.g. the Maps icon).

For example, here's a comparation between the Masonry and Progress Bar icons and their filled versions, where you can see that the readability of the solid icons is reduced compared to their counterparts:
![image](https://user-images.githubusercontent.com/67728772/186395401-45afab9b-a2d0-4c63-9442-211751279be0.png)

Of course, the style (and colour too) can be adjusted and molded the more I progress with them, these are just some starting points and would love to hear your thoughts on this.

**Comment by HardeepAsrani** [comment]
They look nice, for Masonry in particular I feel like it looks more like FSE icon than Masonry. Maybe you can add something inside the boxes to make it feel like they're images? Not sure if that will look fine or too busy.

**Comment by poorse02** [comment]
I believe it'd be too crowded if I added something inside the boxes because the icon is already on the verge of being too crowded (but works like this) as it is.
Even if I add some simple shades, it becomes very busy and way less readable:
 
![image](https://user-images.githubusercontent.com/67728772/186899134-6382bfd8-a22f-4526-9eab-d77039203d41.png)

**Comment by ineagu** [comment]
good work @poorse02. For the the popup icon in still confusing since is looking exactly like a open in a new tab icon.

The best I found is this : https://www.iconfinder.com/icons/4298685/popup_ui_window_icon

**Comment by JohnPixle** [comment]
Apologies for being late to the party! I really like the style and the resolution of the icons @poorse02, nice work 👍🏻 
I feel that the density and detail are quite good and consistent across all icons, which is the most important things imho.

I also believe that Outline style will work better than the filled version in terms of readability, but we can evaluate this more when you design more icons.

The popup icon needs some work indeed, I like the icon Ionut suggested, but I believe you might need to simplify the shape in order to match the current style. 

Will be keeping an eye on Figma, and see if I can add some references for inspiration. 
Many thanks!

**Comment by HardeepAsrani** [comment]
Any updates on this?

**Comment by poorse02** [comment]
Hello again, sorry for the late updates, been working on more fronts lately. Happy to announce that I've drafted all the icons and that they're in their (mostly) final form - I'll adjust them after your feedback if it's not clear visually what they're supposed to be or any other changes.

Please take a look in the [Figma file](https://www.figma.com/file/dLNEZwxPRfh5X906ClqdA0/Otter-Icons-Revamp?node-id=217%3A141). The new icons are found in the _Progress_ page in the _New Icons_ frame.

I've kept the same style I've established in the beginning - round corners and rectangles while avoiding other sorts of shapes (when possible) and filled items used sparingly on accent elements of the icons.

Now, there are 2 things that we should discuss:
- deprecated block icons
- instance icons

**Deprecated block icons** - I have a question here. Can users who've used deprecated blocks on their sites (and didn't remove them so far) still access the blocks? Because if so, there might be the issue if we should update the deprecated blocks icons too and if it's worth it.
**Instance icons** - I've noticed that in the WP building space there are different icons used for parent blocks and child blocks, meaning that for _Column**s**_ there's an icon and for _Column_ there's another one (albeit a variation of it) - see screenshot below. 

![image](https://user-images.githubusercontent.com/67728772/200282065-408ef6e0-5c9b-4b54-badf-2f598153bfbc.png)

This is something we can talk about towards the end, but it's worth mentioning and thinking about it. There's already some experimenting on this matter in the Figma File (in the same frame as the new icons).

Any questions or feedback are much appreciated!

**Comment by JohnPixle** [comment]
Very nice work @poorse02 really like them. They are consistent, friendly and convey the message much better. Are you open to some optimisation suggestions regarding pixelation and the pixel grid?

I noticed that in 1:1 view some of the icons look fuzzy, and this is because the lines and shapes are not 100% aligned with the pixel grid. This is not hard to do in the existing icons, and I can help you out with it. But if we make it, the icons will look quite crisp.

Below is a before / after view after I aligned them with the pixel grid. This of course will not be possible with EVERY icon, but it's worth a shot whenever we can do it.

![Screenshot 2022-11-07 at 12 52 46 PM](https://user-images.githubusercontent.com/4193672/200292935-57159782-78c3-4926-a91c-48043587ebce.png)


[Here is a quick video](https://www.loom.com/share/4384c565513a4de4822398ae7618bb87) where I explain the whole pixel grid concept. Let me know if it makes sense.

**Comment by poorse02** [comment]
Thank you for the advice, John! Didn't know about this effect. I used half pixel distance to let the elements breathe a little but it seems it had the opposite effect, good to know 👍. I'll adjust them accordingly.

**Comment by ineagu** [comment]
@HardeepAsrani is all good here? I think we can also pick a unique color for the Otter icons, something lite aligned with our branding. Do you like the idea @JohnPixle? or prefer to stick with black and try to have some Otter branding to them?

**Comment by mghenciu** [comment]
I know you are quite busy with the FSE themes, John.
So I've tried something in [Figma](https://www.figma.com/file/dLNEZwxPRfh5X906ClqdA0/Otter-Icons-Revamp?node-id=402%3A2375&t=GjdJhGkcA17avM8e-3) , using the **Default Otter color** (not a great result) and using a **Gradient** (attached)
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/52494172/206519903-d2353abf-0d04-4d23-b9de-b5616f6f3ad4.png">

I think this should also have an option in the Otter Panel/Dashboard, so users choose if they want a distinctive color or the Default one.

___
From this preview, I think it may be worth **exploring increasing a bit the Stroke width**. At this point our strokes look a bit too small, compared to the Core Icons, imo.

Let me know your thoughts, when you get some time.

**Comment by HardeepAsrani** [comment]
@mghenciu I'd be against allowing an option to toggle the color of the icons. It's giving the user too much choice over an option that doesn't really affect them. We can choose the color and go with it, just making sure it works nicely with light/dark mode.

**Comment by ineagu** [comment]
Those are good to me and I agree with Hardeep.Sent from my iPhoneOn Dec 9, 2022, at 00:50, Hardeep Asrani ***@***.***> wrote:﻿
@mghenciu I'd be against allowing an option to toggle the color of the icons. It's giving the user too much choice over an option that doesn't really affect them. We can choose the color and go with it, just making sure it works nicely with light/dark mode.

**Comment by poorse02** [comment]
As discussed with Mihai and here as well, I've revised the final version of the icons and also did the icons for child blocks. I think the current gradient is a good fit for the icons and isn't too over the top 👍 . 
The icons can be found [here](https://www.figma.com/file/dLNEZwxPRfh5X906ClqdA0/Otter-Icons-Revamp?node-id=217%3A1141&t=KnykLWq5KDSXgz7P-1), in the _Icons - NEW_ frame.
As for the deprecated blocks, I think the best we can do is just change the colour for them.

**Comment by HardeepAsrani** [comment]
They've live, thank you @poorse02 for the work!
