### ISSUE TITLE
"Saving CSS" & "CSS Saved" showing up even though I don't have the "Custom CSS Module" enabled

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/otter-blocks#945]
https://www.loom.com/share/0f7789ebbb8d47c69a4d639d52c52f23

**Comment by cristianraiber** [comment]
@HardeepAsrani - cool, how do I disable it then? :)

**Comment by HardeepAsrani** [comment]
@cristianraiber You can't really, it's there so people don't just close the browser tab before the CSS has saved. Instead of rendering the CSS inline in HTML tags, like Gutenberg blocks normally are meant to do, we save them in a CSS file instead to improve performance and to make blocks more flexible to update for developers.

**Comment by HardeepAsrani** [comment]
@cristianraiber Haha, yea, that's a known issue. We fixed this a few days back https://github.com/Codeinwp/otter-blocks/issues/896 and it should be out in the next release. Currently it wasn't trigger the request multiple times but was just trigger the notifications.

**Comment by cristianraiber** [comment]
Lovely to learn that it's already been fixed.

**Comment by HardeepAsrani** [comment]
Closing it then. Thanks!
