### ISSUE TITLE
Visibility conditions don't work for Widgets in Customizer

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#999]
### Description:
If you set visibility conditions for a widget, they will be ignored. It does not matter if the widget is placed in the header, footer, sidebar, or any other place where you can set a widget. I think this is related to the fact that after you set a condition, the Customizer does not prompt you to publish changes and there is no save button to confirm that the changes have actually been applied. 

If you create a condition for a widget, then you exit the customizer and enter it again, and you'll see that the condition hasn't been saved. (sidebar widgets)

If you place the Widget in the Footer for example, then when you enter the Customizer again, you'll see that the "Block Condition" label is placed on the said widget, however, when you expand the settings for that widget, the rules are empty.

https://user-images.githubusercontent.com/82535909/175951154-8257dd95-2ddd-4ad7-8a8d-f5ad4738abb2.mp4

The conditions do work as expected on the items placed on the page itself using the Page Editor tool.

### How to reproduce:

1. Have Otter Installed on your WP instance
2. Add a widget in the Sidebar and one in the Footer/Header (from Otter, Theme, Core etc) 
3. Set the Visibility Conditions of the said widgets. ( I have set them to only display for Logged In Administrators)
4. Save and Publish the content (doesn't work for widgets, only for Page Items)
5. Exit the Customizer
6. Enter the Customizer again
7. Observe how the conditions are not registered for Sidebar widgets
8. Observe how the "Block Conditions" label appears for Footer Widgets but they are not set when expanded

### Expected behaviour:
Visibility Conditions are respected for widgets too

### Current behaviour:
Visibility Conditions are ignored for widgets

### Reference:
[User reported here](https://secure.helpscout.net/conversation/1932124192/327480?folderId=212390)

### Technical info
* WordPress version: 6.0
* Plugin version: 2.0.5

**Comment by HardeepAsrani** [comment]
@Skystream96 Have you try with the development branch? https://github.com/Codeinwp/otter-blocks/pull/978#issuecomment-1157064770 - I tried on my side with logged in/out on sidebar and it was working fine.

Let me know.

**Comment by HardeepAsrani** [comment]
@Skystream96 

Okay, so the issue here is that your Publish button doesn't become active hence your data isn't really being saved so the conditions can't work unless saved.

However, when I try it from my side the button becomes active and I can save it too, so I wonder why it doesn't become active for you.

For testing, if you just add condition and make some other change in Customizer then the publish button will become active so you can test that.

Anyway, so let me test with a couple of browsers and see if the publish button staying inactive happens somewhere else too.

Thanks for the report!

**Comment by Skystream96** [comment]
Hi @HardeepAsrani ,

Here is the video showing the exact behavior in Firefox, it is the same in Chrome, Brave and Safari. I also commented it in case it helps https://vertis.d.pr/PIfeAu

Here are the credentials:
 Admin area URL: https://practicefall.s1-tastewp.com/wp-admin 
 Username: mateithemeisle 
 Password: Y8jEpmjm7T8 

Also, there were no errors in the console in the private window. There were some tastewp-related ones when using the customizer but I don't think they are related.

Hopefully, this clears things up!

Let me know if I can help with anything else or if you want to jump on a short call or something.

**Comment by HardeepAsrani** [comment]
Thank you, I was able to reproduce it now!

**Comment by Soare-Robert-Daniel** [comment]
I done some testing and the Customiser has some weird behaviour:

- If you a condition and the change the value, the Publish button is grey, indicating that there is no change.
- If you add a new group, then Publish button activates and the page can be saved.

Is like customiser making shallow test (like the length of the array) rather that a deep one (the content).

**Comment by selul** [comment]
@Soare-Robert-Daniel, I think the notice is very good, and this is a good workaround, can't we go further and fix the behavior? I was wondering if we can't use the customer js API to trigger the change.

**Comment by HardeepAsrani** [comment]
@selul The issue is that Customizer makes a very shallow comparison on the attribute object and doesn't take into account its nested nature of it. The solution might be to remove the attribute and save it again to avoid the comparison...unless the comparison is done on Publish not changed in which case we're doomed. 😄

**Comment by selul** [comment]
@abaicus @preda-bogdan @cristian-ungureanu  maybe you have some insights too since you worked a lot with customizer API.

**Comment by abaicus** [comment]
@selul I already talked with @Soare-Robert-Daniel about this, and it turns out that triggering changes for the widgets builder is really weird.

Widget changes get saved as dirty values in `wp.customize.dirtyValues()`, but I am not sure how this gets triggered or if it's enough to trigger a proper change.

Maybe there is a way to dispatch a trigger to the customizer. The package for this can be found [here](https://github.com/WordPress/gutenberg/tree/trunk/packages/customize-widgets).

**Comment by HardeepAsrani** [comment]
I'm not sure if we can trigger that change for a particular change in attributes but might be worth checking out if possible @Soare-Robert-Daniel
